import * as stylex from '@stylexjs/stylex';
import { youRefTypeface } from './ref.stylex';

export const youSysColor = stylex.defineVars({
  background: '254 247 255',
  error: '179 38 30',
  errorContainer: '249 222 220',
  inverseOnSurface: '245 239 247',
  inversePrimary: '208 188 255',
  inverseSurface: '50 47 53',
  onBackground: '29 27 32',
  onError: '255 255 255',
  onErrorContainer: '140 29 24',
  onPrimary: '255 255 255',
  onPrimaryContainer: '79 55 139',
  onPrimaryFixed: '33 0 93',
  onPrimaryFixedVariant: '79 55 139',
  onSecondary: '255 255 255',
  onSecondaryContainer: '74 68 88',
  onSecondaryFixed: '29 25 43',
  onSecondaryFixedVariant: '74 68 88',
  onSurface: '29 27 32',
  onSurfaceVariant: '73 69 79',
  onTertiary: '255 255 255',
  onTertiaryContainer: '99 59 72',
  onTertiaryFixed: '49 17 29',
  onTertiaryFixedVariant: '99 59 72',
  outline: '121 116 126',
  outlineVariant: '202 196 208',
  primary: '103 80 164',
  primaryContainer: '234 221 255',
  primaryFixed: '234 221 255',
  primaryFixedDim: '208 188 255',
  scrim: '0 0 0',
  secondary: '98 91 113',
  secondaryContainer: '232 222 248',
  secondaryFixed: '232 222 248',
  secondaryFixedDim: '204 194 220',
  shadow: '0 0 0',
  surface: '254 247 255',
  surfaceBright: '254 247 255',
  surfaceContainer: '243 237 247',
  surfaceContainerHigh: '236 230 240',
  surfaceContainerHighest: '230 224 233',
  surfaceContainerLow: '247 242 250',
  surfaceContainerLowest: '255 255 255',
  surfaceDim: '222 216 225',
  surfaceTint: '103 80 164',
  surfaceVariant: '231 224 236',
  tertiary: '125 82 96',
  tertiaryContainer: '255 216 228',
  tertiaryFixed: '255 216 228',
  tertiaryFixedDim: '239 184 200',
});

export const youSysElevation = stylex.defineVars({
  level0: '',
  level1: '',
  level2: '',
  level3: '',
  level4: '',
  level5: '',
});

export const youSysShape = stylex.defineVars({
  cornerFull: stylex.types.length(9999),
  cornerExtraLarge: stylex.types.length(28),
  cornerLarge: stylex.types.length(16),
  cornerMedium: stylex.types.length(12),
  cornerSmall: stylex.types.length(8),
  cornerExtraSmall: stylex.types.length(4),
  cornerNone: stylex.types.length(0),
});

export const youSysMotion = stylex.defineVars({
  easingEmphasizedDecelerate: 'cubic-bezier(0.05, 0.7, 0.1, 1)',
  easingEmphasizedAccelerate: 'cubic-bezier(0.3, 0, 0.8, 0.15)',
  easingStandardDecelerate: 'cubic-bezier(0, 0, 0, 1)',
  easingStandardAccelerate: 'cubic-bezier(0.3, 0, 1, 1)',
  easingStandard: 'cubic-bezier(0.2, 0, 0, 1)',
  easingEmphasized: 'cubic-bezier(0.2, 0, 0, 1)',
  easingLinear: 'cubic-bezier(0, 0, 1, 1)',
  easingLegacy: 'cubic-bezier(0.4, 0, 0.2, 1)',
  easingLegacyAccelerate: 'cubic-bezier(0.4, 0, 1, 1)',
  easingLegacyDecelerate: 'cubic-bezier(0, 0, 0.2, 1)',

  durationExtraLong4: stylex.types.time('1000ms'),
  durationExtraLong3: stylex.types.time('900ms'),
  durationExtraLong2: stylex.types.time('800ms'),
  durationExtraLong1: stylex.types.time('700ms'),
  durationLong4: stylex.types.time('600ms'),
  durationLong3: stylex.types.time('550ms'),
  durationLong2: stylex.types.time('500ms'),
  durationLong1: stylex.types.time('450ms'),
  durationMedium4: stylex.types.time('400ms'),
  durationMedium3: stylex.types.time('350ms'),
  durationMedium2: stylex.types.time('300ms'),
  durationMedium1: stylex.types.time('250ms'),
  durationShort4: stylex.types.time('200ms'),
  durationShort3: stylex.types.time('150ms'),
  durationShort2: stylex.types.time('100ms'),
  durationShort1: stylex.types.time('50ms'),

  durationEmphasized: stylex.types.time('500ms'),
  durationEmphasizedDecelerate: stylex.types.time('400ms'),
  durationEmphasizedAccelerate: stylex.types.time('200ms'),
  durationStandard: stylex.types.time('300ms'),
  durationStandardDecelerate: stylex.types.time('250ms'),
  durationStandardAccelerate: stylex.types.time('200ms'),
  durationLinear: stylex.types.time('200ms'),
});

export const youSysState = stylex.defineVars({
  pressedStateLayerOpacity: stylex.types.number(0.12),
  focusStateLayerOpacity: stylex.types.number(0.12),
  hoverStateLayerOpacity: stylex.types.number(0.08),
  draggedStateLayerOpacity: stylex.types.number(0.16),
  scrimOpacity: stylex.types.number(0.32),
  shadowOpacity: stylex.types.number(0.4),
  disabledContentOpacity: stylex.types.number(0.38),
  disabledOutlineOpacity: stylex.types.number(0.38),
  disabledContainerOpacity: stylex.types.number(0.12),
});

export const youSysTypescale = stylex.defineVars({
  displayLargeFont: youRefTypeface.brand,
  displayLargeWeight: stylex.types.integer(youRefTypeface.weightRegular),
  displayLargeSize: stylex.types.length(57),
  displayLargeLineHeight: stylex.types.number(1.3),
  displayLargeTracking: stylex.types.length(youRefTypeface.trackingNone),
  displayLargeFontStyle: youRefTypeface.fontStyleNormal,
  displayLargeTextTransform: youRefTypeface.textTransformNone,
  displayLargeTextDecoration: youRefTypeface.textDecorationNone,
  displayMediumFont: youRefTypeface.brand,
  displayMediumWeight: stylex.types.integer(youRefTypeface.weightRegular),
  displayMediumSize: stylex.types.length(45),
  displayMediumLineHeight: stylex.types.number(1.3),
  displayMediumTracking: stylex.types.length(youRefTypeface.trackingNone),
  displayMediumFontStyle: youRefTypeface.fontStyleNormal,
  displayMediumTextTransform: youRefTypeface.textTransformNone,
  displayMediumTextDecoration: youRefTypeface.textDecorationNone,
  displaySmallFont: youRefTypeface.brand,
  displaySmallWeight: stylex.types.integer(youRefTypeface.weightRegular),
  displaySmallSize: stylex.types.length(36),
  displaySmallLineHeight: stylex.types.number(1.3),
  displaySmallTracking: stylex.types.length(youRefTypeface.trackingNone),
  displaySmallFontStyle: youRefTypeface.fontStyleNormal,
  displaySmallTextTransform: youRefTypeface.textTransformNone,
  displaySmallTextDecoration: youRefTypeface.textDecorationNone,
  headlineLargeFont: youRefTypeface.brand,
  headlineLargeWeight: stylex.types.integer(youRefTypeface.weightRegular),
  headlineLargeSize: stylex.types.length(32),
  headlineLargeLineHeight: stylex.types.number(1.3),
  headlineLargeTracking: stylex.types.length(youRefTypeface.trackingNone),
  headlineLargeFontStyle: youRefTypeface.fontStyleNormal,
  headlineLargeTextTransform: youRefTypeface.textTransformNone,
  headlineLargeTextDecoration: youRefTypeface.textDecorationNone,
  headlineMediumFont: youRefTypeface.brand,
  headlineMediumWeight: stylex.types.integer(youRefTypeface.weightRegular),
  headlineMediumSize: stylex.types.length(28),
  headlineMediumLineHeight: stylex.types.number(1.3),
  headlineMediumTracking: stylex.types.length(youRefTypeface.trackingNone),
  headlineMediumFontStyle: youRefTypeface.fontStyleNormal,
  headlineMediumTextTransform: youRefTypeface.textTransformNone,
  headlineMediumTextDecoration: youRefTypeface.textDecorationNone,
  headlineSmallFont: youRefTypeface.brand,
  headlineSmallWeight: stylex.types.integer(youRefTypeface.weightRegular),
  headlineSmallSize: stylex.types.length(24),
  headlineSmallLineHeight: stylex.types.number(1.3),
  headlineSmallTracking: stylex.types.length(youRefTypeface.trackingNone),
  headlineSmallFontStyle: youRefTypeface.fontStyleNormal,
  headlineSmallTextTransform: youRefTypeface.textTransformNone,
  headlineSmallTextDecoration: youRefTypeface.textDecorationNone,
  bodyLargeFont: youRefTypeface.plain,
  bodyLargeWeight: stylex.types.integer(youRefTypeface.weightRegular),
  bodyLargeSize: stylex.types.length(16),
  bodyLargeLineHeight: stylex.types.number(1.6),
  bodyLargeTracking: stylex.types.length(youRefTypeface.trackingNone),
  bodyLargeFontStyle: youRefTypeface.fontStyleNormal,
  bodyLargeTextTransform: youRefTypeface.textTransformNone,
  bodyLargeTextDecoration: youRefTypeface.textDecorationNone,
  bodyMediumFont: youRefTypeface.plain,
  bodyMediumWeight: stylex.types.integer(youRefTypeface.weightRegular),
  bodyMediumSize: stylex.types.length(14),
  bodyMediumLineHeight: stylex.types.number(1.6),
  bodyMediumTracking: stylex.types.length(youRefTypeface.trackingNone),
  bodyMediumFontStyle: youRefTypeface.fontStyleNormal,
  bodyMediumTextTransform: youRefTypeface.textTransformNone,
  bodyMediumTextDecoration: youRefTypeface.textDecorationNone,
  bodySmallFont: youRefTypeface.plain,
  bodySmallWeight: stylex.types.integer(youRefTypeface.weightRegular),
  bodySmallSize: stylex.types.length(12),
  bodySmallLineHeight: stylex.types.number(1.6),
  bodySmallTracking: stylex.types.length(youRefTypeface.trackingNone),
  bodySmallFontStyle: youRefTypeface.fontStyleNormal,
  bodySmallTextTransform: youRefTypeface.textTransformNone,
  bodySmallTextDecoration: youRefTypeface.textDecorationNone,
  labelLargeFont: youRefTypeface.plain,
  labelLargeWeight: stylex.types.integer(youRefTypeface.weightMedium),
  labelLargeSize: stylex.types.length(14),
  labelLargeLineHeight: stylex.types.number(1.3),
  labelLargeTracking: stylex.types.length(youRefTypeface.trackingNone),
  labelLargeFontStyle: youRefTypeface.fontStyleNormal,
  labelLargeTextTransform: youRefTypeface.textTransformNone,
  labelLargeTextDecoration: youRefTypeface.textDecorationNone,
  labelMediumFont: youRefTypeface.plain,
  labelMediumWeight: stylex.types.integer(youRefTypeface.weightMedium),
  labelMediumSize: stylex.types.length(12),
  labelMediumLineHeight: stylex.types.number(1.3),
  labelMediumTracking: stylex.types.length(youRefTypeface.trackingNone),
  labelMediumFontStyle: youRefTypeface.fontStyleNormal,
  labelMediumTextTransform: youRefTypeface.textTransformNone,
  labelMediumTextDecoration: youRefTypeface.textDecorationNone,
  labelSmallFont: youRefTypeface.plain,
  labelSmallWeight: stylex.types.integer(youRefTypeface.weightMedium),
  labelSmallSize: stylex.types.length(11),
  labelSmallLineHeight: stylex.types.number(1.3),
  labelSmallTracking: stylex.types.length(youRefTypeface.trackingNone),
  labelSmallFontStyle: youRefTypeface.fontStyleNormal,
  labelSmallTextTransform: youRefTypeface.textTransformNone,
  labelSmallTextDecoration: youRefTypeface.textDecorationNone,
  titleLargeFont: youRefTypeface.brand,
  titleLargeWeight: stylex.types.integer(youRefTypeface.weightRegular),
  titleLargeSize: stylex.types.length(22),
  titleLargeLineHeight: stylex.types.number(1.3),
  titleLargeTracking: stylex.types.length(youRefTypeface.trackingNone),
  titleLargeFontStyle: youRefTypeface.fontStyleNormal,
  titleLargeTextTransform: youRefTypeface.textTransformNone,
  titleLargeTextDecoration: youRefTypeface.textDecorationNone,
  titleMediumFont: youRefTypeface.plain,
  titleMediumWeight: stylex.types.integer(youRefTypeface.weightMedium),
  titleMediumSize: stylex.types.length(16),
  titleMediumLineHeight: stylex.types.number(1.3),
  titleMediumTracking: stylex.types.length(youRefTypeface.trackingNone),
  titleMediumFontStyle: youRefTypeface.fontStyleNormal,
  titleMediumTextTransform: youRefTypeface.textTransformNone,
  titleMediumTextDecoration: youRefTypeface.textDecorationNone,
  titleSmallFont: youRefTypeface.plain,
  titleSmallWeight: stylex.types.integer(youRefTypeface.weightMedium),
  titleSmallSize: stylex.types.length(14),
  titleSmallLineHeight: stylex.types.number(1.3),
  titleSmallTracking: stylex.types.length(youRefTypeface.trackingNone),
  titleSmallFontStyle: youRefTypeface.fontStyleNormal,
  titleSmallTextTransform: youRefTypeface.textTransformNone,
  titleSmallTextDecoration: youRefTypeface.textDecorationNone,
});
