import * as stylex from '@stylexjs/stylex';
import { youSysTypescale } from './sys.stylex';

export const youPresetTypography = stylex.create({
  displayLarge: {
    fontFamily: youSysTypescale.displayLargeFont,
    fontOpticalSizing: 'auto',
    fontSize: youSysTypescale.displayLargeSize,
    fontStyle: youSysTypescale.displayLargeFontStyle,
    fontWeight: youSysTypescale.displayLargeWeight,
    letterSpacing: youSysTypescale.displayLargeTracking,
    lineHeight: youSysTypescale.displayLargeLineHeight,
    textDecoration: youSysTypescale.displayLargeTextDecoration,
    textTransform: youSysTypescale.displayLargeTextTransform,
  },
  displayMedium: {
    fontFamily: youSysTypescale.displayMediumFont,
    fontOpticalSizing: 'auto',
    fontSize: youSysTypescale.displayMediumSize,
    fontStyle: youSysTypescale.displayMediumFontStyle,
    fontWeight: youSysTypescale.displayMediumWeight,
    letterSpacing: youSysTypescale.displayMediumTracking,
    lineHeight: youSysTypescale.displayMediumLineHeight,
    textDecoration: youSysTypescale.displayMediumTextDecoration,
    textTransform: youSysTypescale.displayMediumTextTransform,
  },
  displaySmall: {
    fontFamily: youSysTypescale.displaySmallFont,
    fontOpticalSizing: 'auto',
    fontSize: youSysTypescale.displaySmallSize,
    fontStyle: youSysTypescale.displaySmallFontStyle,
    fontWeight: youSysTypescale.displaySmallWeight,
    letterSpacing: youSysTypescale.displaySmallTracking,
    lineHeight: youSysTypescale.displaySmallLineHeight,
    textDecoration: youSysTypescale.displaySmallTextDecoration,
    textTransform: youSysTypescale.displaySmallTextTransform,
  },
  headlineLarge: {
    fontFamily: youSysTypescale.headlineLargeFont,
    fontOpticalSizing: 'auto',
    fontSize: youSysTypescale.headlineLargeSize,
    fontStyle: youSysTypescale.headlineLargeFontStyle,
    fontWeight: youSysTypescale.headlineLargeWeight,
    letterSpacing: youSysTypescale.headlineLargeTracking,
    lineHeight: youSysTypescale.headlineLargeLineHeight,
    textDecoration: youSysTypescale.headlineLargeTextDecoration,
    textTransform: youSysTypescale.headlineLargeTextTransform,
  },
  headlineMedium: {
    fontFamily: youSysTypescale.headlineMediumFont,
    fontOpticalSizing: 'auto',
    fontSize: youSysTypescale.headlineMediumSize,
    fontStyle: youSysTypescale.headlineMediumFontStyle,
    fontWeight: youSysTypescale.headlineMediumWeight,
    letterSpacing: youSysTypescale.headlineMediumTracking,
    lineHeight: youSysTypescale.headlineMediumLineHeight,
    textDecoration: youSysTypescale.headlineMediumTextDecoration,
    textTransform: youSysTypescale.headlineMediumTextTransform,
  },
  headlineSmall: {
    fontFamily: youSysTypescale.headlineSmallFont,
    fontOpticalSizing: 'auto',
    fontSize: youSysTypescale.headlineSmallSize,
    fontStyle: youSysTypescale.headlineSmallFontStyle,
    fontWeight: youSysTypescale.headlineSmallWeight,
    letterSpacing: youSysTypescale.headlineSmallTracking,
    lineHeight: youSysTypescale.headlineSmallLineHeight,
    textDecoration: youSysTypescale.headlineSmallTextDecoration,
    textTransform: youSysTypescale.headlineSmallTextTransform,
  },
  bodyLarge: {
    fontFamily: youSysTypescale.bodyLargeFont,
    fontOpticalSizing: 'auto',
    fontSize: youSysTypescale.bodyLargeSize,
    fontStyle: youSysTypescale.bodyLargeFontStyle,
    fontWeight: youSysTypescale.bodyLargeWeight,
    letterSpacing: youSysTypescale.bodyLargeTracking,
    lineHeight: youSysTypescale.bodyLargeLineHeight,
    textDecoration: youSysTypescale.bodyLargeTextDecoration,
    textTransform: youSysTypescale.bodyLargeTextTransform,
  },
  bodyMedium: {
    fontFamily: youSysTypescale.bodyMediumFont,
    fontOpticalSizing: 'auto',
    fontSize: youSysTypescale.bodyMediumSize,
    fontStyle: youSysTypescale.bodyMediumFontStyle,
    fontWeight: youSysTypescale.bodyMediumWeight,
    letterSpacing: youSysTypescale.bodyMediumTracking,
    lineHeight: youSysTypescale.bodyMediumLineHeight,
    textDecoration: youSysTypescale.bodyMediumTextDecoration,
    textTransform: youSysTypescale.bodyMediumTextTransform,
  },
  bodySmall: {
    fontFamily: youSysTypescale.bodySmallFont,
    fontOpticalSizing: 'auto',
    fontSize: youSysTypescale.bodySmallSize,
    fontStyle: youSysTypescale.bodySmallFontStyle,
    fontWeight: youSysTypescale.bodySmallWeight,
    letterSpacing: youSysTypescale.bodySmallTracking,
    lineHeight: youSysTypescale.bodySmallLineHeight,
    textDecoration: youSysTypescale.bodySmallTextDecoration,
    textTransform: youSysTypescale.bodySmallTextTransform,
  },
  titleLarge: {
    fontFamily: youSysTypescale.titleLargeFont,
    fontOpticalSizing: 'auto',
    fontSize: youSysTypescale.titleLargeSize,
    fontStyle: youSysTypescale.titleLargeFontStyle,
    fontWeight: youSysTypescale.titleLargeWeight,
    letterSpacing: youSysTypescale.titleLargeTracking,
    lineHeight: youSysTypescale.titleLargeLineHeight,
    textDecoration: youSysTypescale.titleLargeTextDecoration,
    textTransform: youSysTypescale.titleLargeTextTransform,
  },
  titleMedium: {
    fontFamily: youSysTypescale.titleMediumFont,
    fontOpticalSizing: 'auto',
    fontSize: youSysTypescale.titleMediumSize,
    fontStyle: youSysTypescale.titleMediumFontStyle,
    fontWeight: youSysTypescale.titleMediumWeight,
    letterSpacing: youSysTypescale.titleMediumTracking,
    lineHeight: youSysTypescale.titleMediumLineHeight,
    textDecoration: youSysTypescale.titleMediumTextDecoration,
    textTransform: youSysTypescale.titleMediumTextTransform,
  },
  titleSmall: {
    fontFamily: youSysTypescale.titleSmallFont,
    fontOpticalSizing: 'auto',
    fontSize: youSysTypescale.titleSmallSize,
    fontStyle: youSysTypescale.titleSmallFontStyle,
    fontWeight: youSysTypescale.titleSmallWeight,
    letterSpacing: youSysTypescale.titleSmallTracking,
    lineHeight: youSysTypescale.titleSmallLineHeight,
    textDecoration: youSysTypescale.titleSmallTextDecoration,
    textTransform: youSysTypescale.titleSmallTextTransform,
  },
  labelLarge: {
    fontFamily: youSysTypescale.labelLargeFont,
    fontOpticalSizing: 'auto',
    fontSize: youSysTypescale.labelLargeSize,
    fontStyle: youSysTypescale.labelLargeFontStyle,
    fontWeight: youSysTypescale.labelLargeWeight,
    letterSpacing: youSysTypescale.labelLargeTracking,
    lineHeight: youSysTypescale.labelLargeLineHeight,
    textDecoration: youSysTypescale.labelLargeTextDecoration,
    textTransform: youSysTypescale.labelLargeTextTransform,
  },
  labelMedium: {
    fontFamily: youSysTypescale.labelMediumFont,
    fontOpticalSizing: 'auto',
    fontSize: youSysTypescale.labelMediumSize,
    fontStyle: youSysTypescale.labelMediumFontStyle,
    fontWeight: youSysTypescale.labelMediumWeight,
    letterSpacing: youSysTypescale.labelMediumTracking,
    lineHeight: youSysTypescale.labelMediumLineHeight,
    textDecoration: youSysTypescale.labelMediumTextDecoration,
    textTransform: youSysTypescale.labelMediumTextTransform,
  },
  labelSmall: {
    fontFamily: youSysTypescale.labelSmallFont,
    fontOpticalSizing: 'auto',
    fontSize: youSysTypescale.labelSmallSize,
    fontStyle: youSysTypescale.labelSmallFontStyle,
    fontWeight: youSysTypescale.labelSmallWeight,
    letterSpacing: youSysTypescale.labelSmallTracking,
    lineHeight: youSysTypescale.labelSmallLineHeight,
    textDecoration: youSysTypescale.labelSmallTextDecoration,
    textTransform: youSysTypescale.labelSmallTextTransform,
  },
});
