import * as stylex from '@stylexjs/stylex';
import { youSysMotion, youSysTypescale } from './sys.stylex';

export const youPresetTypography = stylex.create({
  displayLarge: {
    fontFamily: youSysTypescale.displayLargeFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.displayLargeSize}/16*1rem)`,
    fontStyle: youSysTypescale.displayLargeFontStyle,
    fontWeight: youSysTypescale.displayLargeWeight,
    letterSpacing: `calc(${youSysTypescale.displayLargeTracking}/${youSysTypescale.displayLargeSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.displayLargeLineHeight}/${youSysTypescale.displayLargeSize})`,
    textDecoration: youSysTypescale.displayLargeTextDecoration,
    textTransform: youSysTypescale.displayLargeTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.displayLargeWght}, 'grad' ${youSysTypescale.displayLargeGrad}, 'wdth' ${youSysTypescale.displayLargeWdth}, 'rond' ${youSysTypescale.displayLargeRond}, 'opsz' ${youSysTypescale.displayLargeOpsz}, 'crsv' ${youSysTypescale.displayLargeCrsv}, 'slnt' ${youSysTypescale.displayLargeSlnt}, 'fill' ${youSysTypescale.displayLargeFill}, 'hexp' ${youSysTypescale.displayLargeHexp}`,
  },
  displayMedium: {
    fontFamily: youSysTypescale.displayMediumFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.displayMediumSize}/16*1rem)`,
    fontStyle: youSysTypescale.displayMediumFontStyle,
    fontWeight: youSysTypescale.displayMediumWeight,
    letterSpacing: `calc(${youSysTypescale.displayMediumTracking}/${youSysTypescale.displayMediumSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.displayMediumLineHeight}/${youSysTypescale.displayMediumSize})`,
    textDecoration: youSysTypescale.displayMediumTextDecoration,
    textTransform: youSysTypescale.displayMediumTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.displayMediumWght}, 'grad' ${youSysTypescale.displayMediumGrad}, 'wdth' ${youSysTypescale.displayMediumWdth}, 'rond' ${youSysTypescale.displayMediumRond}, 'opsz' ${youSysTypescale.displayMediumOpsz}, 'crsv' ${youSysTypescale.displayMediumCrsv}, 'slnt' ${youSysTypescale.displayMediumSlnt}, 'fill' ${youSysTypescale.displayMediumFill}, 'hexp' ${youSysTypescale.displayMediumHexp}`,
  },
  displaySmall: {
    fontFamily: youSysTypescale.displaySmallFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.displaySmallSize}/16*1rem)`,
    fontStyle: youSysTypescale.displaySmallFontStyle,
    fontWeight: youSysTypescale.displaySmallWeight,
    letterSpacing: `calc(${youSysTypescale.displaySmallTracking}/${youSysTypescale.displaySmallSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.displaySmallLineHeight}/${youSysTypescale.displaySmallSize})`,
    textDecoration: youSysTypescale.displaySmallTextDecoration,
    textTransform: youSysTypescale.displaySmallTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.displaySmallWght}, 'grad' ${youSysTypescale.displaySmallGrad}, 'wdth' ${youSysTypescale.displaySmallWdth}, 'rond' ${youSysTypescale.displaySmallRond}, 'opsz' ${youSysTypescale.displaySmallOpsz}, 'crsv' ${youSysTypescale.displaySmallCrsv}, 'slnt' ${youSysTypescale.displaySmallSlnt}, 'fill' ${youSysTypescale.displaySmallFill}, 'hexp' ${youSysTypescale.displaySmallHexp}`,
  },
  headlineLarge: {
    fontFamily: youSysTypescale.headlineLargeFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.headlineLargeSize}/16*1rem)`,
    fontStyle: youSysTypescale.headlineLargeFontStyle,
    fontWeight: youSysTypescale.headlineLargeWeight,
    letterSpacing: `calc(${youSysTypescale.headlineLargeTracking}/${youSysTypescale.headlineLargeSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.headlineLargeLineHeight}/${youSysTypescale.headlineLargeSize})`,
    textDecoration: youSysTypescale.headlineLargeTextDecoration,
    textTransform: youSysTypescale.headlineLargeTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.headlineLargeWght}, 'grad' ${youSysTypescale.headlineLargeGrad}, 'wdth' ${youSysTypescale.headlineLargeWdth}, 'rond' ${youSysTypescale.headlineLargeRond}, 'opsz' ${youSysTypescale.headlineLargeOpsz}, 'crsv' ${youSysTypescale.headlineLargeCrsv}, 'slnt' ${youSysTypescale.headlineLargeSlnt}, 'fill' ${youSysTypescale.headlineLargeFill}, 'hexp' ${youSysTypescale.headlineLargeHexp}`,
  },
  headlineMedium: {
    fontFamily: youSysTypescale.headlineMediumFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.headlineMediumSize}/16*1rem)`,
    fontStyle: youSysTypescale.headlineMediumFontStyle,
    fontWeight: youSysTypescale.headlineMediumWeight,
    letterSpacing: `calc(${youSysTypescale.headlineMediumTracking}/${youSysTypescale.headlineMediumSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.headlineMediumLineHeight}/${youSysTypescale.headlineMediumSize})`,
    textDecoration: youSysTypescale.headlineMediumTextDecoration,
    textTransform: youSysTypescale.headlineMediumTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.headlineMediumWght}, 'grad' ${youSysTypescale.headlineMediumGrad}, 'wdth' ${youSysTypescale.headlineMediumWdth}, 'rond' ${youSysTypescale.headlineMediumRond}, 'opsz' ${youSysTypescale.headlineMediumOpsz}, 'crsv' ${youSysTypescale.headlineMediumCrsv}, 'slnt' ${youSysTypescale.headlineMediumSlnt}, 'fill' ${youSysTypescale.headlineMediumFill}, 'hexp' ${youSysTypescale.headlineMediumHexp}`,
  },
  headlineSmall: {
    fontFamily: youSysTypescale.headlineSmallFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.headlineSmallSize}/16*1rem)`,
    fontStyle: youSysTypescale.headlineSmallFontStyle,
    fontWeight: youSysTypescale.headlineSmallWeight,
    letterSpacing: `calc(${youSysTypescale.headlineSmallTracking}/${youSysTypescale.headlineSmallSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.headlineSmallLineHeight}/${youSysTypescale.headlineSmallSize})`,
    textDecoration: youSysTypescale.headlineSmallTextDecoration,
    textTransform: youSysTypescale.headlineSmallTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.headlineSmallWght}, 'grad' ${youSysTypescale.headlineSmallGrad}, 'wdth' ${youSysTypescale.headlineSmallWdth}, 'rond' ${youSysTypescale.headlineSmallRond}, 'opsz' ${youSysTypescale.headlineSmallOpsz}, 'crsv' ${youSysTypescale.headlineSmallCrsv}, 'slnt' ${youSysTypescale.headlineSmallSlnt}, 'fill' ${youSysTypescale.headlineSmallFill}, 'hexp' ${youSysTypescale.headlineSmallHexp}`,
  },
  bodyLarge: {
    fontFamily: youSysTypescale.bodyLargeFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.bodyLargeSize}/16*1rem)`,
    fontStyle: youSysTypescale.bodyLargeFontStyle,
    fontWeight: youSysTypescale.bodyLargeWeight,
    letterSpacing: `calc(${youSysTypescale.bodyLargeTracking}/${youSysTypescale.bodyLargeSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.bodyLargeLineHeight}/${youSysTypescale.bodyLargeSize})`,
    textDecoration: youSysTypescale.bodyLargeTextDecoration,
    textTransform: youSysTypescale.bodyLargeTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.bodyLargeWght}, 'grad' ${youSysTypescale.bodyLargeGrad}, 'wdth' ${youSysTypescale.bodyLargeWdth}, 'rond' ${youSysTypescale.bodyLargeRond}, 'opsz' ${youSysTypescale.bodyLargeOpsz}, 'crsv' ${youSysTypescale.bodyLargeCrsv}, 'slnt' ${youSysTypescale.bodyLargeSlnt}, 'fill' ${youSysTypescale.bodyLargeFill}, 'hexp' ${youSysTypescale.bodyLargeHexp}`,
  },
  bodyMedium: {
    fontFamily: youSysTypescale.bodyMediumFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.bodyMediumSize}/16*1rem)`,
    fontStyle: youSysTypescale.bodyMediumFontStyle,
    fontWeight: youSysTypescale.bodyMediumWeight,
    letterSpacing: `calc(${youSysTypescale.bodyMediumTracking}/${youSysTypescale.bodyMediumSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.bodyMediumLineHeight}/${youSysTypescale.bodyMediumSize})`,
    textDecoration: youSysTypescale.bodyMediumTextDecoration,
    textTransform: youSysTypescale.bodyMediumTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.bodyMediumWght}, 'grad' ${youSysTypescale.bodyMediumGrad}, 'wdth' ${youSysTypescale.bodyMediumWdth}, 'rond' ${youSysTypescale.bodyMediumRond}, 'opsz' ${youSysTypescale.bodyMediumOpsz}, 'crsv' ${youSysTypescale.bodyMediumCrsv}, 'slnt' ${youSysTypescale.bodyMediumSlnt}, 'fill' ${youSysTypescale.bodyMediumFill}, 'hexp' ${youSysTypescale.bodyMediumHexp}`,
  },
  bodySmall: {
    fontFamily: youSysTypescale.bodySmallFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.bodySmallSize}/16*1rem)`,
    fontStyle: youSysTypescale.bodySmallFontStyle,
    fontWeight: youSysTypescale.bodySmallWeight,
    letterSpacing: `calc(${youSysTypescale.bodySmallTracking}/${youSysTypescale.bodySmallSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.bodySmallLineHeight}/${youSysTypescale.bodySmallSize})`,
    textDecoration: youSysTypescale.bodySmallTextDecoration,
    textTransform: youSysTypescale.bodySmallTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.bodySmallWght}, 'grad' ${youSysTypescale.bodySmallGrad}, 'wdth' ${youSysTypescale.bodySmallWdth}, 'rond' ${youSysTypescale.bodySmallRond}, 'opsz' ${youSysTypescale.bodySmallOpsz}, 'crsv' ${youSysTypescale.bodySmallCrsv}, 'slnt' ${youSysTypescale.bodySmallSlnt}, 'fill' ${youSysTypescale.bodySmallFill}, 'hexp' ${youSysTypescale.bodySmallHexp}`,
  },
  titleLarge: {
    fontFamily: youSysTypescale.titleLargeFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.titleLargeSize}/16*1rem)`,
    fontStyle: youSysTypescale.titleLargeFontStyle,
    fontWeight: youSysTypescale.titleLargeWeight,
    letterSpacing: `calc(${youSysTypescale.titleLargeTracking}/${youSysTypescale.titleLargeSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.titleLargeLineHeight}/${youSysTypescale.titleLargeSize})`,
    textDecoration: youSysTypescale.titleLargeTextDecoration,
    textTransform: youSysTypescale.titleLargeTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.titleLargeWght}, 'grad' ${youSysTypescale.titleLargeGrad}, 'wdth' ${youSysTypescale.titleLargeWdth}, 'rond' ${youSysTypescale.titleLargeRond}, 'opsz' ${youSysTypescale.titleLargeOpsz}, 'crsv' ${youSysTypescale.titleLargeCrsv}, 'slnt' ${youSysTypescale.titleLargeSlnt}, 'fill' ${youSysTypescale.titleLargeFill}, 'hexp' ${youSysTypescale.titleLargeHexp}`,
  },
  titleMedium: {
    fontFamily: youSysTypescale.titleMediumFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.titleMediumSize}/16*1rem)`,
    fontStyle: youSysTypescale.titleMediumFontStyle,
    fontWeight: youSysTypescale.titleMediumWeight,
    letterSpacing: `calc(${youSysTypescale.titleMediumTracking}/${youSysTypescale.titleMediumSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.titleMediumLineHeight}/${youSysTypescale.titleMediumSize})`,
    textDecoration: youSysTypescale.titleMediumTextDecoration,
    textTransform: youSysTypescale.titleMediumTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.titleMediumWght}, 'grad' ${youSysTypescale.titleMediumGrad}, 'wdth' ${youSysTypescale.titleMediumWdth}, 'rond' ${youSysTypescale.titleMediumRond}, 'opsz' ${youSysTypescale.titleMediumOpsz}, 'crsv' ${youSysTypescale.titleMediumCrsv}, 'slnt' ${youSysTypescale.titleMediumSlnt}, 'fill' ${youSysTypescale.titleMediumFill}, 'hexp' ${youSysTypescale.titleMediumHexp}`,
  },
  titleSmall: {
    fontFamily: youSysTypescale.titleSmallFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.titleSmallSize}/16*1rem)`,
    fontStyle: youSysTypescale.titleSmallFontStyle,
    fontWeight: youSysTypescale.titleSmallWeight,
    letterSpacing: `calc(${youSysTypescale.titleSmallTracking}/${youSysTypescale.titleSmallSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.titleSmallLineHeight}/${youSysTypescale.titleSmallSize})`,
    textDecoration: youSysTypescale.titleSmallTextDecoration,
    textTransform: youSysTypescale.titleSmallTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.titleSmallWght}, 'grad' ${youSysTypescale.titleSmallGrad}, 'wdth' ${youSysTypescale.titleSmallWdth}, 'rond' ${youSysTypescale.titleSmallRond}, 'opsz' ${youSysTypescale.titleSmallOpsz}, 'crsv' ${youSysTypescale.titleSmallCrsv}, 'slnt' ${youSysTypescale.titleSmallSlnt}, 'fill' ${youSysTypescale.titleSmallFill}, 'hexp' ${youSysTypescale.titleSmallHexp}`,
  },
  labelLarge: {
    fontFamily: youSysTypescale.labelLargeFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.labelLargeSize}/16*1rem)`,
    fontStyle: youSysTypescale.labelLargeFontStyle,
    fontWeight: youSysTypescale.labelLargeWeight,
    letterSpacing: `calc(${youSysTypescale.labelLargeTracking}/${youSysTypescale.labelLargeSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.labelLargeLineHeight}/${youSysTypescale.labelLargeSize})`,
    textDecoration: youSysTypescale.labelLargeTextDecoration,
    textTransform: youSysTypescale.labelLargeTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.labelLargeWght}, 'grad' ${youSysTypescale.labelLargeGrad}, 'wdth' ${youSysTypescale.labelLargeWdth}, 'rond' ${youSysTypescale.labelLargeRond}, 'opsz' ${youSysTypescale.labelLargeOpsz}, 'crsv' ${youSysTypescale.labelLargeCrsv}, 'slnt' ${youSysTypescale.labelLargeSlnt}, 'fill' ${youSysTypescale.labelLargeFill}, 'hexp' ${youSysTypescale.labelLargeHexp}`,
  },
  labelMedium: {
    fontFamily: youSysTypescale.labelMediumFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.labelMediumSize}/16*1rem)`,
    fontStyle: youSysTypescale.labelMediumFontStyle,
    fontWeight: youSysTypescale.labelMediumWeight,
    letterSpacing: `calc(${youSysTypescale.labelMediumTracking}/${youSysTypescale.labelMediumSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.labelMediumLineHeight}/${youSysTypescale.labelMediumSize})`,
    textDecoration: youSysTypescale.labelMediumTextDecoration,
    textTransform: youSysTypescale.labelMediumTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.labelMediumWght}, 'grad' ${youSysTypescale.labelMediumGrad}, 'wdth' ${youSysTypescale.labelMediumWdth}, 'rond' ${youSysTypescale.labelMediumRond}, 'opsz' ${youSysTypescale.labelMediumOpsz}, 'crsv' ${youSysTypescale.labelMediumCrsv}, 'slnt' ${youSysTypescale.labelMediumSlnt}, 'fill' ${youSysTypescale.labelMediumFill}, 'hexp' ${youSysTypescale.labelMediumHexp}`,
  },
  labelSmall: {
    fontFamily: youSysTypescale.labelSmallFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.labelSmallSize}/16*1rem)`,
    fontStyle: youSysTypescale.labelSmallFontStyle,
    fontWeight: youSysTypescale.labelSmallWeight,
    letterSpacing: `calc(${youSysTypescale.labelSmallTracking}/${youSysTypescale.labelSmallSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.labelSmallLineHeight}/${youSysTypescale.labelSmallSize})`,
    textDecoration: youSysTypescale.labelSmallTextDecoration,
    textTransform: youSysTypescale.labelSmallTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.labelSmallWght}, 'grad' ${youSysTypescale.labelSmallGrad}, 'wdth' ${youSysTypescale.labelSmallWdth}, 'rond' ${youSysTypescale.labelSmallRond}, 'opsz' ${youSysTypescale.labelSmallOpsz}, 'crsv' ${youSysTypescale.labelSmallCrsv}, 'slnt' ${youSysTypescale.labelSmallSlnt}, 'fill' ${youSysTypescale.labelSmallFill}, 'hexp' ${youSysTypescale.labelSmallHexp}`,
  },
  emphasizedDisplayLarge: {
    fontFamily: youSysTypescale.emphasizedDisplayLargeFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.emphasizedDisplayLargeSize}/16*1rem)`,
    fontStyle: youSysTypescale.emphasizedDisplayLargeFontStyle,
    fontWeight: youSysTypescale.emphasizedDisplayLargeWeight,
    letterSpacing: `calc(${youSysTypescale.emphasizedDisplayLargeTracking}/${youSysTypescale.emphasizedDisplayLargeSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.emphasizedDisplayLargeLineHeight}/${youSysTypescale.emphasizedDisplayLargeSize})`,
    textDecoration: youSysTypescale.emphasizedDisplayLargeTextDecoration,
    textTransform: youSysTypescale.emphasizedDisplayLargeTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.emphasizedDisplayLargeWght}, 'grad' ${youSysTypescale.emphasizedDisplayLargeGrad}, 'wdth' ${youSysTypescale.emphasizedDisplayLargeWdth}, 'rond' ${youSysTypescale.emphasizedDisplayLargeRond}, 'opsz' ${youSysTypescale.emphasizedDisplayLargeOpsz}, 'crsv' ${youSysTypescale.emphasizedDisplayLargeCrsv}, 'slnt' ${youSysTypescale.emphasizedDisplayLargeSlnt}, 'fill' ${youSysTypescale.emphasizedDisplayLargeFill}, 'hexp' ${youSysTypescale.emphasizedDisplayLargeHexp}`,
  },
  emphasizedDisplayMedium: {
    fontFamily: youSysTypescale.emphasizedDisplayMediumFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.emphasizedDisplayMediumSize}/16*1rem)`,
    fontStyle: youSysTypescale.emphasizedDisplayMediumFontStyle,
    fontWeight: youSysTypescale.emphasizedDisplayMediumWeight,
    letterSpacing: `calc(${youSysTypescale.emphasizedDisplayMediumTracking}/${youSysTypescale.emphasizedDisplayMediumSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.emphasizedDisplayMediumLineHeight}/${youSysTypescale.emphasizedDisplayMediumSize})`,
    textDecoration: youSysTypescale.emphasizedDisplayMediumTextDecoration,
    textTransform: youSysTypescale.emphasizedDisplayMediumTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.emphasizedDisplayMediumWght}, 'grad' ${youSysTypescale.emphasizedDisplayMediumGrad}, 'wdth' ${youSysTypescale.emphasizedDisplayMediumWdth}, 'rond' ${youSysTypescale.emphasizedDisplayMediumRond}, 'opsz' ${youSysTypescale.emphasizedDisplayMediumOpsz}, 'crsv' ${youSysTypescale.emphasizedDisplayMediumCrsv}, 'slnt' ${youSysTypescale.emphasizedDisplayMediumSlnt}, 'fill' ${youSysTypescale.emphasizedDisplayMediumFill}, 'hexp' ${youSysTypescale.emphasizedDisplayMediumHexp}`,
  },
  emphasizedDisplaySmall: {
    fontFamily: youSysTypescale.emphasizedDisplaySmallFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.emphasizedDisplaySmallSize}/16*1rem)`,
    fontStyle: youSysTypescale.emphasizedDisplaySmallFontStyle,
    fontWeight: youSysTypescale.emphasizedDisplaySmallWeight,
    letterSpacing: `calc(${youSysTypescale.emphasizedDisplaySmallTracking}/${youSysTypescale.emphasizedDisplaySmallSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.emphasizedDisplaySmallLineHeight}/${youSysTypescale.emphasizedDisplaySmallSize})`,
    textDecoration: youSysTypescale.emphasizedDisplaySmallTextDecoration,
    textTransform: youSysTypescale.emphasizedDisplaySmallTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.emphasizedDisplaySmallWght}, 'grad' ${youSysTypescale.emphasizedDisplaySmallGrad}, 'wdth' ${youSysTypescale.emphasizedDisplaySmallWdth}, 'rond' ${youSysTypescale.emphasizedDisplaySmallRond}, 'opsz' ${youSysTypescale.emphasizedDisplaySmallOpsz}, 'crsv' ${youSysTypescale.emphasizedDisplaySmallCrsv}, 'slnt' ${youSysTypescale.emphasizedDisplaySmallSlnt}, 'fill' ${youSysTypescale.emphasizedDisplaySmallFill}, 'hexp' ${youSysTypescale.emphasizedDisplaySmallHexp}`,
  },
  emphasizedHeadlineLarge: {
    fontFamily: youSysTypescale.emphasizedHeadlineLargeFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.emphasizedHeadlineLargeSize}/16*1rem)`,
    fontStyle: youSysTypescale.emphasizedHeadlineLargeFontStyle,
    fontWeight: youSysTypescale.emphasizedHeadlineLargeWeight,
    letterSpacing: `calc(${youSysTypescale.emphasizedHeadlineLargeTracking}/${youSysTypescale.emphasizedHeadlineLargeSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.emphasizedHeadlineLargeLineHeight}/${youSysTypescale.emphasizedHeadlineLargeSize})`,
    textDecoration: youSysTypescale.emphasizedHeadlineLargeTextDecoration,
    textTransform: youSysTypescale.emphasizedHeadlineLargeTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.emphasizedHeadlineLargeWght}, 'grad' ${youSysTypescale.emphasizedHeadlineLargeGrad}, 'wdth' ${youSysTypescale.emphasizedHeadlineLargeWdth}, 'rond' ${youSysTypescale.emphasizedHeadlineLargeRond}, 'opsz' ${youSysTypescale.emphasizedHeadlineLargeOpsz}, 'crsv' ${youSysTypescale.emphasizedHeadlineLargeCrsv}, 'slnt' ${youSysTypescale.emphasizedHeadlineLargeSlnt}, 'fill' ${youSysTypescale.emphasizedHeadlineLargeFill}, 'hexp' ${youSysTypescale.emphasizedHeadlineLargeHexp}`,
  },
  emphasizedHeadlineMedium: {
    fontFamily: youSysTypescale.emphasizedHeadlineMediumFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.emphasizedHeadlineMediumSize}/16*1rem)`,
    fontStyle: youSysTypescale.emphasizedHeadlineMediumFontStyle,
    fontWeight: youSysTypescale.emphasizedHeadlineMediumWeight,
    letterSpacing: `calc(${youSysTypescale.emphasizedHeadlineMediumTracking}/${youSysTypescale.emphasizedHeadlineMediumSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.emphasizedHeadlineMediumLineHeight}/${youSysTypescale.emphasizedHeadlineMediumSize})`,
    textDecoration: youSysTypescale.emphasizedHeadlineMediumTextDecoration,
    textTransform: youSysTypescale.emphasizedHeadlineMediumTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.emphasizedHeadlineMediumWght}, 'grad' ${youSysTypescale.emphasizedHeadlineMediumGrad}, 'wdth' ${youSysTypescale.emphasizedHeadlineMediumWdth}, 'rond' ${youSysTypescale.emphasizedHeadlineMediumRond}, 'opsz' ${youSysTypescale.emphasizedHeadlineMediumOpsz}, 'crsv' ${youSysTypescale.emphasizedHeadlineMediumCrsv}, 'slnt' ${youSysTypescale.emphasizedHeadlineMediumSlnt}, 'fill' ${youSysTypescale.emphasizedHeadlineMediumFill}, 'hexp' ${youSysTypescale.emphasizedHeadlineMediumHexp}`,
  },
  emphasizedHeadlineSmall: {
    fontFamily: youSysTypescale.emphasizedHeadlineSmallFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.emphasizedHeadlineSmallSize}/16*1rem)`,
    fontStyle: youSysTypescale.emphasizedHeadlineSmallFontStyle,
    fontWeight: youSysTypescale.emphasizedHeadlineSmallWeight,
    letterSpacing: `calc(${youSysTypescale.emphasizedHeadlineSmallTracking}/${youSysTypescale.emphasizedHeadlineSmallSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.emphasizedHeadlineSmallLineHeight}/${youSysTypescale.emphasizedHeadlineSmallSize})`,
    textDecoration: youSysTypescale.emphasizedHeadlineSmallTextDecoration,
    textTransform: youSysTypescale.emphasizedHeadlineSmallTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.emphasizedHeadlineSmallWght}, 'grad' ${youSysTypescale.emphasizedHeadlineSmallGrad}, 'wdth' ${youSysTypescale.emphasizedHeadlineSmallWdth}, 'rond' ${youSysTypescale.emphasizedHeadlineSmallRond}, 'opsz' ${youSysTypescale.emphasizedHeadlineSmallOpsz}, 'crsv' ${youSysTypescale.emphasizedHeadlineSmallCrsv}, 'slnt' ${youSysTypescale.emphasizedHeadlineSmallSlnt}, 'fill' ${youSysTypescale.emphasizedHeadlineSmallFill}, 'hexp' ${youSysTypescale.emphasizedHeadlineSmallHexp}`,
  },
  emphasizedBodyLarge: {
    fontFamily: youSysTypescale.emphasizedBodyLargeFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.emphasizedBodyLargeSize}/16*1rem)`,
    fontStyle: youSysTypescale.emphasizedBodyLargeFontStyle,
    fontWeight: youSysTypescale.emphasizedBodyLargeWeight,
    letterSpacing: `calc(${youSysTypescale.emphasizedBodyLargeTracking}/${youSysTypescale.emphasizedBodyLargeSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.emphasizedBodyLargeLineHeight}/${youSysTypescale.emphasizedBodyLargeSize})`,
    textDecoration: youSysTypescale.emphasizedBodyLargeTextDecoration,
    textTransform: youSysTypescale.emphasizedBodyLargeTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.emphasizedBodyLargeWght}, 'grad' ${youSysTypescale.emphasizedBodyLargeGrad}, 'wdth' ${youSysTypescale.emphasizedBodyLargeWdth}, 'rond' ${youSysTypescale.emphasizedBodyLargeRond}, 'opsz' ${youSysTypescale.emphasizedBodyLargeOpsz}, 'crsv' ${youSysTypescale.emphasizedBodyLargeCrsv}, 'slnt' ${youSysTypescale.emphasizedBodyLargeSlnt}, 'fill' ${youSysTypescale.emphasizedBodyLargeFill}, 'hexp' ${youSysTypescale.emphasizedBodyLargeHexp}`,
  },
  emphasizedBodyMedium: {
    fontFamily: youSysTypescale.emphasizedBodyMediumFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.emphasizedBodyMediumSize}/16*1rem)`,
    fontStyle: youSysTypescale.emphasizedBodyMediumFontStyle,
    fontWeight: youSysTypescale.emphasizedBodyMediumWeight,
    letterSpacing: `calc(${youSysTypescale.emphasizedBodyMediumTracking}/${youSysTypescale.emphasizedBodyMediumSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.emphasizedBodyMediumLineHeight}/${youSysTypescale.emphasizedBodyMediumSize})`,
    textDecoration: youSysTypescale.emphasizedBodyMediumTextDecoration,
    textTransform: youSysTypescale.emphasizedBodyMediumTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.emphasizedBodyMediumWght}, 'grad' ${youSysTypescale.emphasizedBodyMediumGrad}, 'wdth' ${youSysTypescale.emphasizedBodyMediumWdth}, 'rond' ${youSysTypescale.emphasizedBodyMediumRond}, 'opsz' ${youSysTypescale.emphasizedBodyMediumOpsz}, 'crsv' ${youSysTypescale.emphasizedBodyMediumCrsv}, 'slnt' ${youSysTypescale.emphasizedBodyMediumSlnt}, 'fill' ${youSysTypescale.emphasizedBodyMediumFill}, 'hexp' ${youSysTypescale.emphasizedBodyMediumHexp}`,
  },
  emphasizedBodySmall: {
    fontFamily: youSysTypescale.emphasizedBodySmallFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.emphasizedBodySmallSize}/16*1rem)`,
    fontStyle: youSysTypescale.emphasizedBodySmallFontStyle,
    fontWeight: youSysTypescale.emphasizedBodySmallWeight,
    letterSpacing: `calc(${youSysTypescale.emphasizedBodySmallTracking}/${youSysTypescale.emphasizedBodySmallSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.emphasizedBodySmallLineHeight}/${youSysTypescale.emphasizedBodySmallSize})`,
    textDecoration: youSysTypescale.emphasizedBodySmallTextDecoration,
    textTransform: youSysTypescale.emphasizedBodySmallTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.emphasizedBodySmallWght}, 'grad' ${youSysTypescale.emphasizedBodySmallGrad}, 'wdth' ${youSysTypescale.emphasizedBodySmallWdth}, 'rond' ${youSysTypescale.emphasizedBodySmallRond}, 'opsz' ${youSysTypescale.emphasizedBodySmallOpsz}, 'crsv' ${youSysTypescale.emphasizedBodySmallCrsv}, 'slnt' ${youSysTypescale.emphasizedBodySmallSlnt}, 'fill' ${youSysTypescale.emphasizedBodySmallFill}, 'hexp' ${youSysTypescale.emphasizedBodySmallHexp}`,
  },
  emphasizedTitleLarge: {
    fontFamily: youSysTypescale.emphasizedTitleLargeFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.emphasizedTitleLargeSize}/16*1rem)`,
    fontStyle: youSysTypescale.emphasizedTitleLargeFontStyle,
    fontWeight: youSysTypescale.emphasizedTitleLargeWeight,
    letterSpacing: `calc(${youSysTypescale.emphasizedTitleLargeTracking}/${youSysTypescale.emphasizedTitleLargeSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.emphasizedTitleLargeLineHeight}/${youSysTypescale.emphasizedTitleLargeSize})`,
    textDecoration: youSysTypescale.emphasizedTitleLargeTextDecoration,
    textTransform: youSysTypescale.emphasizedTitleLargeTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.emphasizedTitleLargeWght}, 'grad' ${youSysTypescale.emphasizedTitleLargeGrad}, 'wdth' ${youSysTypescale.emphasizedTitleLargeWdth}, 'rond' ${youSysTypescale.emphasizedTitleLargeRond}, 'opsz' ${youSysTypescale.emphasizedTitleLargeOpsz}, 'crsv' ${youSysTypescale.emphasizedTitleLargeCrsv}, 'slnt' ${youSysTypescale.emphasizedTitleLargeSlnt}, 'fill' ${youSysTypescale.emphasizedTitleLargeFill}, 'hexp' ${youSysTypescale.emphasizedTitleLargeHexp}`,
  },
  emphasizedTitleMedium: {
    fontFamily: youSysTypescale.emphasizedTitleMediumFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.emphasizedTitleMediumSize}/16*1rem)`,
    fontStyle: youSysTypescale.emphasizedTitleMediumFontStyle,
    fontWeight: youSysTypescale.emphasizedTitleMediumWeight,
    letterSpacing: `calc(${youSysTypescale.emphasizedTitleMediumTracking}/${youSysTypescale.emphasizedTitleMediumSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.emphasizedTitleMediumLineHeight}/${youSysTypescale.emphasizedTitleMediumSize})`,
    textDecoration: youSysTypescale.emphasizedTitleMediumTextDecoration,
    textTransform: youSysTypescale.emphasizedTitleMediumTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.emphasizedTitleMediumWght}, 'grad' ${youSysTypescale.emphasizedTitleMediumGrad}, 'wdth' ${youSysTypescale.emphasizedTitleMediumWdth}, 'rond' ${youSysTypescale.emphasizedTitleMediumRond}, 'opsz' ${youSysTypescale.emphasizedTitleMediumOpsz}, 'crsv' ${youSysTypescale.emphasizedTitleMediumCrsv}, 'slnt' ${youSysTypescale.emphasizedTitleMediumSlnt}, 'fill' ${youSysTypescale.emphasizedTitleMediumFill}, 'hexp' ${youSysTypescale.emphasizedTitleMediumHexp}`,
  },
  emphasizedTitleSmall: {
    fontFamily: youSysTypescale.emphasizedTitleSmallFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.emphasizedTitleSmallSize}/16*1rem)`,
    fontStyle: youSysTypescale.emphasizedTitleSmallFontStyle,
    fontWeight: youSysTypescale.emphasizedTitleSmallWeight,
    letterSpacing: `calc(${youSysTypescale.emphasizedTitleSmallTracking}/${youSysTypescale.emphasizedTitleSmallSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.emphasizedTitleSmallLineHeight}/${youSysTypescale.emphasizedTitleSmallSize})`,
    textDecoration: youSysTypescale.emphasizedTitleSmallTextDecoration,
    textTransform: youSysTypescale.emphasizedTitleSmallTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.emphasizedTitleSmallWght}, 'grad' ${youSysTypescale.emphasizedTitleSmallGrad}, 'wdth' ${youSysTypescale.emphasizedTitleSmallWdth}, 'rond' ${youSysTypescale.emphasizedTitleSmallRond}, 'opsz' ${youSysTypescale.emphasizedTitleSmallOpsz}, 'crsv' ${youSysTypescale.emphasizedTitleSmallCrsv}, 'slnt' ${youSysTypescale.emphasizedTitleSmallSlnt}, 'fill' ${youSysTypescale.emphasizedTitleSmallFill}, 'hexp' ${youSysTypescale.emphasizedTitleSmallHexp}`,
  },
  emphasizedLabelLarge: {
    fontFamily: youSysTypescale.emphasizedLabelLargeFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.emphasizedLabelLargeSize}/16*1rem)`,
    fontStyle: youSysTypescale.emphasizedLabelLargeFontStyle,
    fontWeight: youSysTypescale.emphasizedLabelLargeWeight,
    letterSpacing: `calc(${youSysTypescale.emphasizedLabelLargeTracking}/${youSysTypescale.emphasizedLabelLargeSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.emphasizedLabelLargeLineHeight}/${youSysTypescale.emphasizedLabelLargeSize})`,
    textDecoration: youSysTypescale.emphasizedLabelLargeTextDecoration,
    textTransform: youSysTypescale.emphasizedLabelLargeTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.emphasizedLabelLargeWght}, 'grad' ${youSysTypescale.emphasizedLabelLargeGrad}, 'wdth' ${youSysTypescale.emphasizedLabelLargeWdth}, 'rond' ${youSysTypescale.emphasizedLabelLargeRond}, 'opsz' ${youSysTypescale.emphasizedLabelLargeOpsz}, 'crsv' ${youSysTypescale.emphasizedLabelLargeCrsv}, 'slnt' ${youSysTypescale.emphasizedLabelLargeSlnt}, 'fill' ${youSysTypescale.emphasizedLabelLargeFill}, 'hexp' ${youSysTypescale.emphasizedLabelLargeHexp}`,
  },
  emphasizedLabelMedium: {
    fontFamily: youSysTypescale.emphasizedLabelMediumFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.emphasizedLabelMediumSize}/16*1rem)`,
    fontStyle: youSysTypescale.emphasizedLabelMediumFontStyle,
    fontWeight: youSysTypescale.emphasizedLabelMediumWeight,
    letterSpacing: `calc(${youSysTypescale.emphasizedLabelMediumTracking}/${youSysTypescale.emphasizedLabelMediumSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.emphasizedLabelMediumLineHeight}/${youSysTypescale.emphasizedLabelMediumSize})`,
    textDecoration: youSysTypescale.emphasizedLabelMediumTextDecoration,
    textTransform: youSysTypescale.emphasizedLabelMediumTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.emphasizedLabelMediumWght}, 'grad' ${youSysTypescale.emphasizedLabelMediumGrad}, 'wdth' ${youSysTypescale.emphasizedLabelMediumWdth}, 'rond' ${youSysTypescale.emphasizedLabelMediumRond}, 'opsz' ${youSysTypescale.emphasizedLabelMediumOpsz}, 'crsv' ${youSysTypescale.emphasizedLabelMediumCrsv}, 'slnt' ${youSysTypescale.emphasizedLabelMediumSlnt}, 'fill' ${youSysTypescale.emphasizedLabelMediumFill}, 'hexp' ${youSysTypescale.emphasizedLabelMediumHexp}`,
  },
  emphasizedLabelSmall: {
    fontFamily: youSysTypescale.emphasizedLabelSmallFont,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${youSysTypescale.emphasizedLabelSmallSize}/16*1rem)`,
    fontStyle: youSysTypescale.emphasizedLabelSmallFontStyle,
    fontWeight: youSysTypescale.emphasizedLabelSmallWeight,
    letterSpacing: `calc(${youSysTypescale.emphasizedLabelSmallTracking}/${youSysTypescale.emphasizedLabelSmallSize}*1em)`,
    lineHeight: `calc(${youSysTypescale.emphasizedLabelSmallLineHeight}/${youSysTypescale.emphasizedLabelSmallSize})`,
    textDecoration: youSysTypescale.emphasizedLabelSmallTextDecoration,
    textTransform: youSysTypescale.emphasizedLabelSmallTextTransform,
    fontVariationSettings: `'wght' ${youSysTypescale.emphasizedLabelSmallWght}, 'grad' ${youSysTypescale.emphasizedLabelSmallGrad}, 'wdth' ${youSysTypescale.emphasizedLabelSmallWdth}, 'rond' ${youSysTypescale.emphasizedLabelSmallRond}, 'opsz' ${youSysTypescale.emphasizedLabelSmallOpsz}, 'crsv' ${youSysTypescale.emphasizedLabelSmallCrsv}, 'slnt' ${youSysTypescale.emphasizedLabelSmallSlnt}, 'fill' ${youSysTypescale.emphasizedLabelSmallFill}, 'hexp' ${youSysTypescale.emphasizedLabelSmallHexp}`,
  },
});

export const youPresetMotion = stylex.create({
  emphasized: {
    transitionTimingFunction: youSysMotion.easingEmphasized,
    transitionDuration: youSysMotion.durationEmphasized,
  },
  emphasizedAccelerate: {
    transitionTimingFunction: youSysMotion.easingEmphasizedAccelerate,
    transitionDuration: youSysMotion.durationEmphasizedAccelerate,
  },
  emphasizedDecelerate: {
    transitionTimingFunction: youSysMotion.easingEmphasizedDecelerate,
    transitionDuration: youSysMotion.durationEmphasizedDecelerate,
  },
  standard: {
    transitionTimingFunction: youSysMotion.easingStandard,
    transitionDuration: youSysMotion.durationStandard,
  },
  standardAccelerate: {
    transitionTimingFunction: youSysMotion.easingStandardAccelerate,
    transitionDuration: youSysMotion.durationStandardAccelerate,
  },
  standardDecelerate: {
    transitionTimingFunction: youSysMotion.easingStandardDecelerate,
    transitionDuration: youSysMotion.durationStandardDecelerate,
  },
  linear: {
    transitionTimingFunction: youSysMotion.easingLinear,
    transitionDuration: youSysMotion.durationLinear,
  },
  legacy: {
    transitionTimingFunction: youSysMotion.easingLegacy,
    transitionDuration: youSysMotion.durationMedium2,
  },
  legacyAccelerate: {
    transitionTimingFunction: youSysMotion.easingLegacyAccelerate,
    transitionDuration: youSysMotion.durationShort4,
  },
  legacyDecelerate: {
    transitionTimingFunction: youSysMotion.easingLegacyDecelerate,
    transitionDuration: youSysMotion.durationMedium1,
  },
  expressiveFastSpatial: {
    transitionTimingFunction: youSysMotion.easingExpressiveFastSpatial,
    transitionDuration: youSysMotion.durationExpressiveFastSpatial,
  },
  expressiveDefaultSpatial: {
    transitionTimingFunction: youSysMotion.easingExpressiveDefaultSpatial,
    transitionDuration: youSysMotion.durationExpressiveDefaultSpatial,
  },
  expressiveSlowSpatial: {
    transitionTimingFunction: youSysMotion.easingExpressiveSlowSpatial,
    transitionDuration: youSysMotion.durationExpressiveSlowSpatial,
  },
  expressiveFastEffects: {
    transitionTimingFunction: youSysMotion.easingExpressiveFastEffects,
    transitionDuration: youSysMotion.durationExpressiveFastEffects,
  },
  expressiveDefaultEffects: {
    transitionTimingFunction: youSysMotion.easingExpressiveDefaultEffects,
    transitionDuration: youSysMotion.durationExpressiveDefaultEffects,
  },
  expressiveSlowEffects: {
    transitionTimingFunction: youSysMotion.easingExpressiveSlowEffects,
    transitionDuration: youSysMotion.durationExpressiveSlowEffects,
  },
  standardFastSpatial: {
    transitionTimingFunction: youSysMotion.easingStandardFastSpatial,
    transitionDuration: youSysMotion.durationStandardFastSpatial,
  },
  standardDefaultSpatial: {
    transitionTimingFunction: youSysMotion.easingStandardDefaultSpatial,
    transitionDuration: youSysMotion.durationStandardDefaultSpatial,
  },
  standardSlowSpatial: {
    transitionTimingFunction: youSysMotion.easingStandardSlowSpatial,
    transitionDuration: youSysMotion.durationStandardSlowSpatial,
  },
  standardFastEffects: {
    transitionTimingFunction: youSysMotion.easingStandardFastEffects,
    transitionDuration: youSysMotion.durationStandardFastEffects,
  },
  standardDefaultEffects: {
    transitionTimingFunction: youSysMotion.easingStandardDefaultEffects,
    transitionDuration: youSysMotion.durationStandardDefaultEffects,
  },
  standardSlowEffects: {
    transitionTimingFunction: youSysMotion.easingStandardSlowEffects,
    transitionDuration: youSysMotion.durationStandardSlowEffects,
  },
});
