import * as stylex from '@stylexjs/stylex';
import { youPalleteDefault } from './palette.stylex';
import { youRefTypeface } from './ref.stylex';

export const youSysColor = stylex.defineVars({
  background: youPalleteDefault.background,
  error: youPalleteDefault.error,
  errorContainer: youPalleteDefault.errorContainer,
  inverseOnSurface: youPalleteDefault.inverseOnSurface,
  inversePrimary: youPalleteDefault.inversePrimary,
  inverseSurface: youPalleteDefault.inverseSurface,
  onBackground: youPalleteDefault.onBackground,
  onError: youPalleteDefault.onError,
  onErrorContainer: youPalleteDefault.onErrorContainer,
  onPrimary: youPalleteDefault.onPrimary,
  onPrimaryContainer: youPalleteDefault.onPrimaryContainer,
  onPrimaryFixed: youPalleteDefault.onPrimaryFixed,
  onPrimaryFixedVariant: youPalleteDefault.onPrimaryFixedVariant,
  onSecondary: youPalleteDefault.onSecondary,
  onSecondaryContainer: youPalleteDefault.onSecondaryContainer,
  onSecondaryFixed: youPalleteDefault.onSecondaryFixed,
  onSecondaryFixedVariant: youPalleteDefault.onSecondaryFixedVariant,
  onSurface: youPalleteDefault.onSurface,
  onSurfaceVariant: youPalleteDefault.onSurfaceVariant,
  onTertiary: youPalleteDefault.onTertiary,
  onTertiaryContainer: youPalleteDefault.onTertiaryContainer,
  onTertiaryFixed: youPalleteDefault.onTertiaryFixed,
  onTertiaryFixedVariant: youPalleteDefault.onTertiaryFixedVariant,
  outline: youPalleteDefault.outline,
  outlineVariant: youPalleteDefault.outlineVariant,
  primary: youPalleteDefault.primary,
  primaryContainer: youPalleteDefault.primaryContainer,
  primaryFixed: youPalleteDefault.primaryFixed,
  primaryFixedDim: youPalleteDefault.primaryFixedDim,
  scrim: youPalleteDefault.scrim,
  secondary: youPalleteDefault.secondary,
  secondaryContainer: youPalleteDefault.secondaryContainer,
  secondaryFixed: youPalleteDefault.secondaryFixed,
  secondaryFixedDim: youPalleteDefault.secondaryFixedDim,
  shadow: youPalleteDefault.shadow,
  surface: youPalleteDefault.surface,
  surfaceBright: youPalleteDefault.surfaceBright,
  surfaceContainer: youPalleteDefault.surfaceContainer,
  surfaceContainerHigh: youPalleteDefault.surfaceContainerHigh,
  surfaceContainerHighest: youPalleteDefault.surfaceContainerHighest,
  surfaceContainerLow: youPalleteDefault.surfaceContainerLow,
  surfaceContainerLowest: youPalleteDefault.surfaceContainerLowest,
  surfaceDim: youPalleteDefault.surfaceDim,
  surfaceTint: youPalleteDefault.surfaceTint,
  surfaceVariant: youPalleteDefault.surfaceVariant,
  tertiary: youPalleteDefault.tertiary,
  tertiaryContainer: youPalleteDefault.tertiaryContainer,
  tertiaryFixed: youPalleteDefault.tertiaryFixed,
  tertiaryFixedDim: youPalleteDefault.tertiaryFixedDim,
});

export const youSysElevation = stylex.defineVars({
  level0: '',
  level1: '',
  level2: '',
  level3: '',
  level4: '',
  level5: '',
});

export const youSysShape = stylex.defineVars({
  cornerFull: stylex.types.length(9999),
  cornerExtraExtraLarge: stylex.types.length(48),
  cornerExtraLargeIncreased: stylex.types.length(32),
  cornerExtraLarge: stylex.types.length(28),
  cornerLargeIncreased: stylex.types.length(20),
  cornerLarge: stylex.types.length(16),
  cornerMedium: stylex.types.length(12),
  cornerSmall: stylex.types.length(8),
  cornerExtraSmall: stylex.types.length(4),
  cornerNone: stylex.types.length(0),
});

export const youSysMotion = stylex.defineVars({
  // legacy
  easingEmphasizedDecelerate: 'cubic-bezier(0.05, 0.7, 0.1, 1)',
  easingEmphasizedAccelerate: 'cubic-bezier(0.3, 0, 0.8, 0.15)',
  easingStandardDecelerate: 'cubic-bezier(0, 0, 0, 1)',
  easingStandardAccelerate: 'cubic-bezier(0.3, 0, 1, 1)',
  easingStandard: 'cubic-bezier(0.2, 0, 0, 1)',
  easingEmphasized: 'cubic-bezier(0.2, 0, 0, 1)',
  easingLinear: 'cubic-bezier(0, 0, 1, 1)',
  easingLegacy: 'cubic-bezier(0.4, 0, 0.2, 1)',
  easingLegacyAccelerate: 'cubic-bezier(0.4, 0, 1, 1)',
  easingLegacyDecelerate: 'cubic-bezier(0, 0, 0.2, 1)',

  durationExtraLong4: stylex.types.time('1000ms'),
  durationExtraLong3: stylex.types.time('900ms'),
  durationExtraLong2: stylex.types.time('800ms'),
  durationExtraLong1: stylex.types.time('700ms'),
  durationLong4: stylex.types.time('600ms'),
  durationLong3: stylex.types.time('550ms'),
  durationLong2: stylex.types.time('500ms'),
  durationLong1: stylex.types.time('450ms'),
  durationMedium4: stylex.types.time('400ms'),
  durationMedium3: stylex.types.time('350ms'),
  durationMedium2: stylex.types.time('300ms'),
  durationMedium1: stylex.types.time('250ms'),
  durationShort4: stylex.types.time('200ms'),
  durationShort3: stylex.types.time('150ms'),
  durationShort2: stylex.types.time('100ms'),
  durationShort1: stylex.types.time('50ms'),

  durationEmphasized: stylex.types.time('500ms'),
  durationEmphasizedDecelerate: stylex.types.time('400ms'),
  durationEmphasizedAccelerate: stylex.types.time('200ms'),
  durationStandard: stylex.types.time('300ms'),
  durationStandardDecelerate: stylex.types.time('250ms'),
  durationStandardAccelerate: stylex.types.time('200ms'),
  durationLinear: stylex.types.time('200ms'),

  // expressive
  easingExpressiveFastSpatial: 'cubic-bezier(0.42, 1.67, 0.21, 0.90)',
  easingExpressiveDefaultSpatial: 'cubic-bezier(0.38, 1.21, 0.22, 1.00)',
  easingExpressiveSlowSpatial: 'cubic-bezier(0.39, 1.29, 0.35, 0.98)',
  easingExpressiveFastEffects: 'cubic-bezier(0.31, 0.94, 0.34, 1.00)',
  easingExpressiveDefaultEffects: 'cubic-bezier(0.34, 0.80, 0.34, 1.00)',
  easingExpressiveSlowEffects: 'cubic-bezier(0.34, 0.88, 0.34, 1.00)',

  easingStandardFastSpatial: 'cubic-bezier(0.27, 1.06, 0.18, 1.00)',
  easingStandardDefaultSpatial: 'cubic-bezier(0.27, 1.06, 0.18, 1.00)',
  easingStandardSlowSpatial: 'cubic-bezier(0.27, 1.06, 0.18, 1.00)',
  easingStandardFastEffects: 'cubic-bezier(0.31, 0.94, 0.34, 1.00)',
  easingStandardDefaultEffects: 'cubic-bezier(0.34, 0.80, 0.34, 1.00)',
  easingStandardSlowEffects: 'cubic-bezier(0.34, 0.88, 0.34, 1.00)',

  durationExpressiveFastSpatial: stylex.types.time('350ms'),
  durationExpressiveDefaultSpatial: stylex.types.time('500ms'),
  durationExpressiveSlowSpatial: stylex.types.time('650ms'),
  durationExpressiveFastEffects: stylex.types.time('150ms'),
  durationExpressiveDefaultEffects: stylex.types.time('200ms'),
  durationExpressiveSlowEffects: stylex.types.time('300ms'),

  durationStandardFastSpatial: stylex.types.time('350ms'),
  durationStandardDefaultSpatial: stylex.types.time('500ms'),
  durationStandardSlowSpatial: stylex.types.time('750ms'),
  durationStandardFastEffects: stylex.types.time('150ms'),
  durationStandardDefaultEffects: stylex.types.time('200ms'),
  durationStandardSlowEffects: stylex.types.time('300ms'),
});

export const youSysState = stylex.defineVars({
  pressedStateLayerOpacity: stylex.types.number(0.12),
  focusStateLayerOpacity: stylex.types.number(0.12),
  hoverStateLayerOpacity: stylex.types.number(0.08),
  draggedStateLayerOpacity: stylex.types.number(0.16),
  scrimOpacity: stylex.types.number(0.32),
  shadowOpacity: stylex.types.number(0.4),
  disabledContentOpacity: stylex.types.number(0.38),
  disabledOutlineOpacity: stylex.types.number(0.38),
  disabledContainerOpacity: stylex.types.number(0.12),
});

export const youSysTypescale = stylex.defineVars({
  displayLargeFont: youRefTypeface.brand,
  displayLargeWeight: stylex.types.integer(youRefTypeface.weightRegular),
  displayLargeSize: stylex.types.length(57),
  displayLargeLineHeight: stylex.types.number(1.3),
  displayLargeTracking: stylex.types.length(youRefTypeface.trackingNone),
  displayLargeFontStyle: youRefTypeface.fontStyleNormal,
  displayLargeTextTransform: youRefTypeface.textTransformNone,
  displayLargeTextDecoration: youRefTypeface.textDecorationNone,
  displayMediumFont: youRefTypeface.brand,
  displayMediumWeight: stylex.types.integer(youRefTypeface.weightRegular),
  displayMediumSize: stylex.types.length(45),
  displayMediumLineHeight: stylex.types.number(1.3),
  displayMediumTracking: stylex.types.length(youRefTypeface.trackingNone),
  displayMediumFontStyle: youRefTypeface.fontStyleNormal,
  displayMediumTextTransform: youRefTypeface.textTransformNone,
  displayMediumTextDecoration: youRefTypeface.textDecorationNone,
  displaySmallFont: youRefTypeface.brand,
  displaySmallWeight: stylex.types.integer(youRefTypeface.weightRegular),
  displaySmallSize: stylex.types.length(36),
  displaySmallLineHeight: stylex.types.number(1.3),
  displaySmallTracking: stylex.types.length(youRefTypeface.trackingNone),
  displaySmallFontStyle: youRefTypeface.fontStyleNormal,
  displaySmallTextTransform: youRefTypeface.textTransformNone,
  displaySmallTextDecoration: youRefTypeface.textDecorationNone,
  headlineLargeFont: youRefTypeface.brand,
  headlineLargeWeight: stylex.types.integer(youRefTypeface.weightRegular),
  headlineLargeSize: stylex.types.length(32),
  headlineLargeLineHeight: stylex.types.number(1.3),
  headlineLargeTracking: stylex.types.length(youRefTypeface.trackingNone),
  headlineLargeFontStyle: youRefTypeface.fontStyleNormal,
  headlineLargeTextTransform: youRefTypeface.textTransformNone,
  headlineLargeTextDecoration: youRefTypeface.textDecorationNone,
  headlineMediumFont: youRefTypeface.brand,
  headlineMediumWeight: stylex.types.integer(youRefTypeface.weightRegular),
  headlineMediumSize: stylex.types.length(28),
  headlineMediumLineHeight: stylex.types.number(1.3),
  headlineMediumTracking: stylex.types.length(youRefTypeface.trackingNone),
  headlineMediumFontStyle: youRefTypeface.fontStyleNormal,
  headlineMediumTextTransform: youRefTypeface.textTransformNone,
  headlineMediumTextDecoration: youRefTypeface.textDecorationNone,
  headlineSmallFont: youRefTypeface.brand,
  headlineSmallWeight: stylex.types.integer(youRefTypeface.weightRegular),
  headlineSmallSize: stylex.types.length(24),
  headlineSmallLineHeight: stylex.types.number(1.3),
  headlineSmallTracking: stylex.types.length(youRefTypeface.trackingNone),
  headlineSmallFontStyle: youRefTypeface.fontStyleNormal,
  headlineSmallTextTransform: youRefTypeface.textTransformNone,
  headlineSmallTextDecoration: youRefTypeface.textDecorationNone,
  bodyLargeFont: youRefTypeface.plain,
  bodyLargeWeight: stylex.types.integer(youRefTypeface.weightRegular),
  bodyLargeSize: stylex.types.length(16),
  bodyLargeLineHeight: stylex.types.number(1.6),
  bodyLargeTracking: stylex.types.length(youRefTypeface.trackingNone),
  bodyLargeFontStyle: youRefTypeface.fontStyleNormal,
  bodyLargeTextTransform: youRefTypeface.textTransformNone,
  bodyLargeTextDecoration: youRefTypeface.textDecorationNone,
  bodyMediumFont: youRefTypeface.plain,
  bodyMediumWeight: stylex.types.integer(youRefTypeface.weightRegular),
  bodyMediumSize: stylex.types.length(14),
  bodyMediumLineHeight: stylex.types.number(1.6),
  bodyMediumTracking: stylex.types.length(youRefTypeface.trackingNone),
  bodyMediumFontStyle: youRefTypeface.fontStyleNormal,
  bodyMediumTextTransform: youRefTypeface.textTransformNone,
  bodyMediumTextDecoration: youRefTypeface.textDecorationNone,
  bodySmallFont: youRefTypeface.plain,
  bodySmallWeight: stylex.types.integer(youRefTypeface.weightRegular),
  bodySmallSize: stylex.types.length(12),
  bodySmallLineHeight: stylex.types.number(1.6),
  bodySmallTracking: stylex.types.length(youRefTypeface.trackingNone),
  bodySmallFontStyle: youRefTypeface.fontStyleNormal,
  bodySmallTextTransform: youRefTypeface.textTransformNone,
  bodySmallTextDecoration: youRefTypeface.textDecorationNone,
  labelLargeFont: youRefTypeface.plain,
  labelLargeWeight: stylex.types.integer(youRefTypeface.weightMedium),
  labelLargeSize: stylex.types.length(14),
  labelLargeLineHeight: stylex.types.number(1.3),
  labelLargeTracking: stylex.types.length(youRefTypeface.trackingNone),
  labelLargeFontStyle: youRefTypeface.fontStyleNormal,
  labelLargeTextTransform: youRefTypeface.textTransformNone,
  labelLargeTextDecoration: youRefTypeface.textDecorationNone,
  labelMediumFont: youRefTypeface.plain,
  labelMediumWeight: stylex.types.integer(youRefTypeface.weightMedium),
  labelMediumSize: stylex.types.length(12),
  labelMediumLineHeight: stylex.types.number(1.3),
  labelMediumTracking: stylex.types.length(youRefTypeface.trackingNone),
  labelMediumFontStyle: youRefTypeface.fontStyleNormal,
  labelMediumTextTransform: youRefTypeface.textTransformNone,
  labelMediumTextDecoration: youRefTypeface.textDecorationNone,
  labelSmallFont: youRefTypeface.plain,
  labelSmallWeight: stylex.types.integer(youRefTypeface.weightMedium),
  labelSmallSize: stylex.types.length(11),
  labelSmallLineHeight: stylex.types.number(1.3),
  labelSmallTracking: stylex.types.length(youRefTypeface.trackingNone),
  labelSmallFontStyle: youRefTypeface.fontStyleNormal,
  labelSmallTextTransform: youRefTypeface.textTransformNone,
  labelSmallTextDecoration: youRefTypeface.textDecorationNone,
  titleLargeFont: youRefTypeface.brand,
  titleLargeWeight: stylex.types.integer(youRefTypeface.weightRegular),
  titleLargeSize: stylex.types.length(22),
  titleLargeLineHeight: stylex.types.number(1.3),
  titleLargeTracking: stylex.types.length(youRefTypeface.trackingNone),
  titleLargeFontStyle: youRefTypeface.fontStyleNormal,
  titleLargeTextTransform: youRefTypeface.textTransformNone,
  titleLargeTextDecoration: youRefTypeface.textDecorationNone,
  titleMediumFont: youRefTypeface.plain,
  titleMediumWeight: stylex.types.integer(youRefTypeface.weightMedium),
  titleMediumSize: stylex.types.length(16),
  titleMediumLineHeight: stylex.types.number(1.3),
  titleMediumTracking: stylex.types.length(youRefTypeface.trackingNone),
  titleMediumFontStyle: youRefTypeface.fontStyleNormal,
  titleMediumTextTransform: youRefTypeface.textTransformNone,
  titleMediumTextDecoration: youRefTypeface.textDecorationNone,
  titleSmallFont: youRefTypeface.plain,
  titleSmallWeight: stylex.types.integer(youRefTypeface.weightMedium),
  titleSmallSize: stylex.types.length(14),
  titleSmallLineHeight: stylex.types.number(1.3),
  titleSmallTracking: stylex.types.length(youRefTypeface.trackingNone),
  titleSmallFontStyle: youRefTypeface.fontStyleNormal,
  titleSmallTextTransform: youRefTypeface.textTransformNone,
  titleSmallTextDecoration: youRefTypeface.textDecorationNone,
});
