import * as stylex from '@stylexjs/stylex';
import { youPalleteDefault } from './palette.stylex';
import { youRefTypeface } from './ref.stylex';

export const youSysColor = stylex.defineVars({
  background: youPalleteDefault.background,
  error: youPalleteDefault.error,
  errorContainer: youPalleteDefault.errorContainer,
  inverseOnSurface: youPalleteDefault.inverseOnSurface,
  inversePrimary: youPalleteDefault.inversePrimary,
  inverseSurface: youPalleteDefault.inverseSurface,
  onBackground: youPalleteDefault.onBackground,
  onError: youPalleteDefault.onError,
  onErrorContainer: youPalleteDefault.onErrorContainer,
  onPrimary: youPalleteDefault.onPrimary,
  onPrimaryContainer: youPalleteDefault.onPrimaryContainer,
  onPrimaryFixed: youPalleteDefault.onPrimaryFixed,
  onPrimaryFixedVariant: youPalleteDefault.onPrimaryFixedVariant,
  onSecondary: youPalleteDefault.onSecondary,
  onSecondaryContainer: youPalleteDefault.onSecondaryContainer,
  onSecondaryFixed: youPalleteDefault.onSecondaryFixed,
  onSecondaryFixedVariant: youPalleteDefault.onSecondaryFixedVariant,
  onSurface: youPalleteDefault.onSurface,
  onSurfaceVariant: youPalleteDefault.onSurfaceVariant,
  onTertiary: youPalleteDefault.onTertiary,
  onTertiaryContainer: youPalleteDefault.onTertiaryContainer,
  onTertiaryFixed: youPalleteDefault.onTertiaryFixed,
  onTertiaryFixedVariant: youPalleteDefault.onTertiaryFixedVariant,
  outline: youPalleteDefault.outline,
  outlineVariant: youPalleteDefault.outlineVariant,
  primary: youPalleteDefault.primary,
  primaryContainer: youPalleteDefault.primaryContainer,
  primaryFixed: youPalleteDefault.primaryFixed,
  primaryFixedDim: youPalleteDefault.primaryFixedDim,
  scrim: youPalleteDefault.scrim,
  secondary: youPalleteDefault.secondary,
  secondaryContainer: youPalleteDefault.secondaryContainer,
  secondaryFixed: youPalleteDefault.secondaryFixed,
  secondaryFixedDim: youPalleteDefault.secondaryFixedDim,
  shadow: youPalleteDefault.shadow,
  surface: youPalleteDefault.surface,
  surfaceBright: youPalleteDefault.surfaceBright,
  surfaceContainer: youPalleteDefault.surfaceContainer,
  surfaceContainerHigh: youPalleteDefault.surfaceContainerHigh,
  surfaceContainerHighest: youPalleteDefault.surfaceContainerHighest,
  surfaceContainerLow: youPalleteDefault.surfaceContainerLow,
  surfaceContainerLowest: youPalleteDefault.surfaceContainerLowest,
  surfaceDim: youPalleteDefault.surfaceDim,
  surfaceTint: youPalleteDefault.surfaceTint,
  surfaceVariant: youPalleteDefault.surfaceVariant,
  tertiary: youPalleteDefault.tertiary,
  tertiaryContainer: youPalleteDefault.tertiaryContainer,
  tertiaryFixed: youPalleteDefault.tertiaryFixed,
  tertiaryFixedDim: youPalleteDefault.tertiaryFixedDim,
});

export const youSysShape = stylex.defineVars({
  cornerFull: stylex.types.length(9999),
  cornerExtraExtraLarge: stylex.types.length(48),
  cornerExtraLargeIncreased: stylex.types.length(32),
  cornerExtraLarge: stylex.types.length(28),
  cornerLargeIncreased: stylex.types.length(20),
  cornerLarge: stylex.types.length(16),
  cornerMedium: stylex.types.length(12),
  cornerSmall: stylex.types.length(8),
  cornerExtraSmall: stylex.types.length(4),
  cornerNone: stylex.types.length(0),
});

export const youSysMotion = stylex.defineVars({
  easingEmphasizedDecelerate: 'cubic-bezier(0.05, 0.7, 0.1, 1)',
  easingEmphasizedAccelerate: 'cubic-bezier(0.3, 0, 0.8, 0.15)',
  easingStandardDecelerate: 'cubic-bezier(0, 0, 0, 1)',
  easingStandardAccelerate: 'cubic-bezier(0.3, 0, 1, 1)',
  easingStandard: 'cubic-bezier(0.2, 0, 0, 1)',
  easingEmphasized: 'cubic-bezier(0.2, 0, 0, 1)',
  easingLinear: 'cubic-bezier(0, 0, 1, 1)',
  easingLegacy: 'cubic-bezier(0.4, 0, 0.2, 1)',
  easingLegacyAccelerate: 'cubic-bezier(0.4, 0, 1, 1)',
  easingLegacyDecelerate: 'cubic-bezier(0, 0, 0.2, 1)',

  durationExtraLong4: stylex.types.time('1000ms'),
  durationExtraLong3: stylex.types.time('900ms'),
  durationExtraLong2: stylex.types.time('800ms'),
  durationExtraLong1: stylex.types.time('700ms'),
  durationLong4: stylex.types.time('600ms'),
  durationLong3: stylex.types.time('550ms'),
  durationLong2: stylex.types.time('500ms'),
  durationLong1: stylex.types.time('450ms'),
  durationMedium4: stylex.types.time('400ms'),
  durationMedium3: stylex.types.time('350ms'),
  durationMedium2: stylex.types.time('300ms'),
  durationMedium1: stylex.types.time('250ms'),
  durationShort4: stylex.types.time('200ms'),
  durationShort3: stylex.types.time('150ms'),
  durationShort2: stylex.types.time('100ms'),
  durationShort1: stylex.types.time('50ms'),

  durationEmphasized: stylex.types.time('500ms'),
  durationEmphasizedDecelerate: stylex.types.time('400ms'),
  durationEmphasizedAccelerate: stylex.types.time('200ms'),
  durationStandard: stylex.types.time('300ms'),
  durationStandardDecelerate: stylex.types.time('250ms'),
  durationStandardAccelerate: stylex.types.time('200ms'),
  durationLinear: stylex.types.time('200ms'),

  easingExpressiveFastSpatial: 'cubic-bezier(0.42, 1.67, 0.21, 0.90)',
  easingExpressiveDefaultSpatial: 'cubic-bezier(0.38, 1.21, 0.22, 1.00)',
  easingExpressiveSlowSpatial: 'cubic-bezier(0.39, 1.29, 0.35, 0.98)',
  easingExpressiveFastEffects: 'cubic-bezier(0.31, 0.94, 0.34, 1.00)',
  easingExpressiveDefaultEffects: 'cubic-bezier(0.34, 0.80, 0.34, 1.00)',
  easingExpressiveSlowEffects: 'cubic-bezier(0.34, 0.88, 0.34, 1.00)',

  easingStandardFastSpatial: 'cubic-bezier(0.27, 1.06, 0.18, 1.00)',
  easingStandardDefaultSpatial: 'cubic-bezier(0.27, 1.06, 0.18, 1.00)',
  easingStandardSlowSpatial: 'cubic-bezier(0.27, 1.06, 0.18, 1.00)',
  easingStandardFastEffects: 'cubic-bezier(0.31, 0.94, 0.34, 1.00)',
  easingStandardDefaultEffects: 'cubic-bezier(0.34, 0.80, 0.34, 1.00)',
  easingStandardSlowEffects: 'cubic-bezier(0.34, 0.88, 0.34, 1.00)',

  durationExpressiveFastSpatial: stylex.types.time('350ms'),
  durationExpressiveDefaultSpatial: stylex.types.time('500ms'),
  durationExpressiveSlowSpatial: stylex.types.time('650ms'),
  durationExpressiveFastEffects: stylex.types.time('150ms'),
  durationExpressiveDefaultEffects: stylex.types.time('200ms'),
  durationExpressiveSlowEffects: stylex.types.time('300ms'),

  durationStandardFastSpatial: stylex.types.time('350ms'),
  durationStandardDefaultSpatial: stylex.types.time('500ms'),
  durationStandardSlowSpatial: stylex.types.time('750ms'),
  durationStandardFastEffects: stylex.types.time('150ms'),
  durationStandardDefaultEffects: stylex.types.time('200ms'),
  durationStandardSlowEffects: stylex.types.time('300ms'),
});

export const youSysState = stylex.defineVars({
  pressedStateLayerOpacity: stylex.types.number(0.12),
  focusStateLayerOpacity: stylex.types.number(0.12),
  hoverStateLayerOpacity: stylex.types.number(0.08),
  draggedStateLayerOpacity: stylex.types.number(0.16),
  scrimOpacity: stylex.types.number(0.32),
  shadowOpacity: stylex.types.number(0.4),
  disabledContentOpacity: stylex.types.number(0.38),
  disabledOutlineOpacity: stylex.types.number(0.38),
  disabledContainerOpacity: stylex.types.number(0.12),
});

export const youSysTypescale = stylex.defineVars({
  displayLargeFont: youRefTypeface.font,
  displayLargeWeight: stylex.types.integer(400),
  displayLargeSize: stylex.types.integer(57),
  displayLargeLineHeight: stylex.types.integer(64),
  displayLargeTracking: stylex.types.number(-0.25),
  displayLargeWght: stylex.types.integer(400),
  displayLargeOpsz: stylex.types.integer(57),
  displayLargeFontStyle: 'normal',
  displayLargeTextTransform: 'none',
  displayLargeTextDecoration: 'none',
  displayLargeGrad: stylex.types.integer(0),
  displayLargeWdth: stylex.types.integer(100),
  displayLargeRond: stylex.types.integer(0),
  displayLargeCrsv: stylex.types.integer(0),
  displayLargeSlnt: stylex.types.integer(0),
  displayLargeFill: stylex.types.integer(0),
  displayLargeHexp: stylex.types.integer(0),

  displayMediumFont: youRefTypeface.font,
  displayMediumWeight: stylex.types.integer(400),
  displayMediumSize: stylex.types.integer(45),
  displayMediumLineHeight: stylex.types.integer(52),
  displayMediumTracking: stylex.types.number(0),
  displayMediumWght: stylex.types.integer(400),
  displayMediumOpsz: stylex.types.integer(45),
  displayMediumFontStyle: 'normal',
  displayMediumTextTransform: 'none',
  displayMediumTextDecoration: 'none',
  displayMediumGrad: stylex.types.integer(0),
  displayMediumWdth: stylex.types.integer(100),
  displayMediumRond: stylex.types.integer(0),
  displayMediumCrsv: stylex.types.integer(0),
  displayMediumSlnt: stylex.types.integer(0),
  displayMediumFill: stylex.types.integer(0),
  displayMediumHexp: stylex.types.integer(0),

  displaySmallFont: youRefTypeface.font,
  displaySmallWeight: stylex.types.integer(400),
  displaySmallSize: stylex.types.integer(36),
  displaySmallLineHeight: stylex.types.integer(44),
  displaySmallTracking: stylex.types.number(0),
  displaySmallWght: stylex.types.integer(400),
  displaySmallOpsz: stylex.types.integer(36),
  displaySmallFontStyle: 'normal',
  displaySmallTextTransform: 'none',
  displaySmallTextDecoration: 'none',
  displaySmallGrad: stylex.types.integer(0),
  displaySmallWdth: stylex.types.integer(100),
  displaySmallRond: stylex.types.integer(0),
  displaySmallCrsv: stylex.types.integer(0),
  displaySmallSlnt: stylex.types.integer(0),
  displaySmallFill: stylex.types.integer(0),
  displaySmallHexp: stylex.types.integer(0),

  headlineLargeFont: youRefTypeface.font,
  headlineLargeWeight: stylex.types.integer(400),
  headlineLargeSize: stylex.types.integer(32),
  headlineLargeLineHeight: stylex.types.integer(40),
  headlineLargeTracking: stylex.types.number(0),
  headlineLargeWght: stylex.types.integer(400),
  headlineLargeOpsz: stylex.types.integer(32),
  headlineLargeFontStyle: 'normal',
  headlineLargeTextTransform: 'none',
  headlineLargeTextDecoration: 'none',
  headlineLargeGrad: stylex.types.integer(0),
  headlineLargeWdth: stylex.types.integer(100),
  headlineLargeRond: stylex.types.integer(0),
  headlineLargeCrsv: stylex.types.integer(0),
  headlineLargeSlnt: stylex.types.integer(0),
  headlineLargeFill: stylex.types.integer(0),
  headlineLargeHexp: stylex.types.integer(0),

  headlineMediumFont: youRefTypeface.font,
  headlineMediumWeight: stylex.types.integer(400),
  headlineMediumSize: stylex.types.integer(28),
  headlineMediumLineHeight: stylex.types.integer(36),
  headlineMediumTracking: stylex.types.number(0),
  headlineMediumWght: stylex.types.integer(400),
  headlineMediumOpsz: stylex.types.integer(28),
  headlineMediumFontStyle: 'normal',
  headlineMediumTextTransform: 'none',
  headlineMediumTextDecoration: 'none',
  headlineMediumGrad: stylex.types.integer(0),
  headlineMediumWdth: stylex.types.integer(100),
  headlineMediumRond: stylex.types.integer(0),
  headlineMediumCrsv: stylex.types.integer(0),
  headlineMediumSlnt: stylex.types.integer(0),
  headlineMediumFill: stylex.types.integer(0),
  headlineMediumHexp: stylex.types.integer(0),

  headlineSmallFont: youRefTypeface.font,
  headlineSmallWeight: stylex.types.integer(400),
  headlineSmallSize: stylex.types.integer(24),
  headlineSmallLineHeight: stylex.types.integer(32),
  headlineSmallTracking: stylex.types.number(0),
  headlineSmallWght: stylex.types.integer(400),
  headlineSmallOpsz: stylex.types.integer(24),
  headlineSmallFontStyle: 'normal',
  headlineSmallTextTransform: 'none',
  headlineSmallTextDecoration: 'none',
  headlineSmallGrad: stylex.types.integer(0),
  headlineSmallWdth: stylex.types.integer(100),
  headlineSmallRond: stylex.types.integer(0),
  headlineSmallCrsv: stylex.types.integer(0),
  headlineSmallSlnt: stylex.types.integer(0),
  headlineSmallFill: stylex.types.integer(0),
  headlineSmallHexp: stylex.types.integer(0),

  titleLargeFont: youRefTypeface.font,
  titleLargeWeight: stylex.types.integer(400),
  titleLargeSize: stylex.types.integer(22),
  titleLargeLineHeight: stylex.types.integer(28),
  titleLargeTracking: stylex.types.number(0),
  titleLargeWght: stylex.types.integer(400),
  titleLargeOpsz: stylex.types.integer(22),
  titleLargeFontStyle: 'normal',
  titleLargeTextTransform: 'none',
  titleLargeTextDecoration: 'none',
  titleLargeGrad: stylex.types.integer(0),
  titleLargeWdth: stylex.types.integer(100),
  titleLargeRond: stylex.types.integer(0),
  titleLargeCrsv: stylex.types.integer(0),
  titleLargeSlnt: stylex.types.integer(0),
  titleLargeFill: stylex.types.integer(0),
  titleLargeHexp: stylex.types.integer(0),

  titleMediumFont: youRefTypeface.font,
  titleMediumWeight: stylex.types.integer(500),
  titleMediumSize: stylex.types.integer(16),
  titleMediumLineHeight: stylex.types.integer(24),
  titleMediumTracking: stylex.types.number(0.15),
  titleMediumWght: stylex.types.integer(500),
  titleMediumOpsz: stylex.types.integer(16),
  titleMediumFontStyle: 'normal',
  titleMediumTextTransform: 'none',
  titleMediumTextDecoration: 'none',
  titleMediumGrad: stylex.types.integer(0),
  titleMediumWdth: stylex.types.integer(100),
  titleMediumRond: stylex.types.integer(0),
  titleMediumCrsv: stylex.types.integer(0),
  titleMediumSlnt: stylex.types.integer(0),
  titleMediumFill: stylex.types.integer(0),
  titleMediumHexp: stylex.types.integer(0),

  titleSmallFont: youRefTypeface.font,
  titleSmallWeight: stylex.types.integer(500),
  titleSmallSize: stylex.types.integer(14),
  titleSmallLineHeight: stylex.types.integer(20),
  titleSmallTracking: stylex.types.number(0.1),
  titleSmallWght: stylex.types.integer(500),
  titleSmallOpsz: stylex.types.integer(14),
  titleSmallFontStyle: 'normal',
  titleSmallTextTransform: 'none',
  titleSmallTextDecoration: 'none',
  titleSmallGrad: stylex.types.integer(0),
  titleSmallWdth: stylex.types.integer(100),
  titleSmallRond: stylex.types.integer(0),
  titleSmallCrsv: stylex.types.integer(0),
  titleSmallSlnt: stylex.types.integer(0),
  titleSmallFill: stylex.types.integer(0),
  titleSmallHexp: stylex.types.integer(0),

  bodyLargeFont: youRefTypeface.font,
  bodyLargeWeight: stylex.types.integer(400),
  bodyLargeSize: stylex.types.integer(16),
  bodyLargeLineHeight: stylex.types.integer(24),
  bodyLargeTracking: stylex.types.number(0.5),
  bodyLargeWght: stylex.types.integer(400),
  bodyLargeOpsz: stylex.types.integer(16),
  bodyLargeFontStyle: 'normal',
  bodyLargeTextTransform: 'none',
  bodyLargeTextDecoration: 'none',
  bodyLargeGrad: stylex.types.integer(0),
  bodyLargeWdth: stylex.types.integer(100),
  bodyLargeRond: stylex.types.integer(0),
  bodyLargeCrsv: stylex.types.integer(0),
  bodyLargeSlnt: stylex.types.integer(0),
  bodyLargeFill: stylex.types.integer(0),
  bodyLargeHexp: stylex.types.integer(0),

  bodyMediumFont: youRefTypeface.font,
  bodyMediumWeight: stylex.types.integer(400),
  bodyMediumSize: stylex.types.integer(14),
  bodyMediumLineHeight: stylex.types.integer(20),
  bodyMediumTracking: stylex.types.number(0.25),
  bodyMediumWght: stylex.types.integer(400),
  bodyMediumOpsz: stylex.types.integer(14),
  bodyMediumFontStyle: 'normal',
  bodyMediumTextTransform: 'none',
  bodyMediumTextDecoration: 'none',
  bodyMediumGrad: stylex.types.integer(0),
  bodyMediumWdth: stylex.types.integer(100),
  bodyMediumRond: stylex.types.integer(0),
  bodyMediumCrsv: stylex.types.integer(0),
  bodyMediumSlnt: stylex.types.integer(0),
  bodyMediumFill: stylex.types.integer(0),
  bodyMediumHexp: stylex.types.integer(0),

  bodySmallFont: youRefTypeface.font,
  bodySmallWeight: stylex.types.integer(400),
  bodySmallSize: stylex.types.integer(12),
  bodySmallLineHeight: stylex.types.integer(16),
  bodySmallTracking: stylex.types.number(0.4),
  bodySmallWght: stylex.types.integer(400),
  bodySmallOpsz: stylex.types.integer(12),
  bodySmallFontStyle: 'normal',
  bodySmallTextTransform: 'none',
  bodySmallTextDecoration: 'none',
  bodySmallGrad: stylex.types.integer(0),
  bodySmallWdth: stylex.types.integer(100),
  bodySmallRond: stylex.types.integer(0),
  bodySmallCrsv: stylex.types.integer(0),
  bodySmallSlnt: stylex.types.integer(0),
  bodySmallFill: stylex.types.integer(0),
  bodySmallHexp: stylex.types.integer(0),

  labelLargeFont: youRefTypeface.font,
  labelLargeWeight: stylex.types.integer(500),
  labelLargeSize: stylex.types.integer(14),
  labelLargeLineHeight: stylex.types.integer(20),
  labelLargeTracking: stylex.types.number(0.1),
  labelLargeWght: stylex.types.integer(500),
  labelLargeOpsz: stylex.types.integer(14),
  labelLargeFontStyle: 'normal',
  labelLargeTextTransform: 'none',
  labelLargeTextDecoration: 'none',
  labelLargeGrad: stylex.types.integer(0),
  labelLargeWdth: stylex.types.integer(100),
  labelLargeRond: stylex.types.integer(0),
  labelLargeCrsv: stylex.types.integer(0),
  labelLargeSlnt: stylex.types.integer(0),
  labelLargeFill: stylex.types.integer(0),
  labelLargeHexp: stylex.types.integer(0),

  labelMediumFont: youRefTypeface.font,
  labelMediumWeight: stylex.types.integer(500),
  labelMediumSize: stylex.types.integer(12),
  labelMediumLineHeight: stylex.types.integer(16),
  labelMediumTracking: stylex.types.number(0.5),
  labelMediumWght: stylex.types.integer(500),
  labelMediumOpsz: stylex.types.integer(12),
  labelMediumFontStyle: 'normal',
  labelMediumTextTransform: 'none',
  labelMediumTextDecoration: 'none',
  labelMediumGrad: stylex.types.integer(0),
  labelMediumWdth: stylex.types.integer(100),
  labelMediumRond: stylex.types.integer(0),
  labelMediumCrsv: stylex.types.integer(0),
  labelMediumSlnt: stylex.types.integer(0),
  labelMediumFill: stylex.types.integer(0),
  labelMediumHexp: stylex.types.integer(0),

  labelSmallFont: youRefTypeface.font,
  labelSmallWeight: stylex.types.integer(500),
  labelSmallSize: stylex.types.integer(11),
  labelSmallLineHeight: stylex.types.integer(16),
  labelSmallTracking: stylex.types.number(0.5),
  labelSmallWght: stylex.types.integer(500),
  labelSmallOpsz: stylex.types.integer(11),
  labelSmallFontStyle: 'normal',
  labelSmallTextTransform: 'none',
  labelSmallTextDecoration: 'none',
  labelSmallGrad: stylex.types.integer(0),
  labelSmallWdth: stylex.types.integer(100),
  labelSmallRond: stylex.types.integer(0),
  labelSmallCrsv: stylex.types.integer(0),
  labelSmallSlnt: stylex.types.integer(0),
  labelSmallFill: stylex.types.integer(0),
  labelSmallHexp: stylex.types.integer(0),

  emphasizedDisplayLargeFont: youRefTypeface.font,
  emphasizedDisplayLargeWeight: stylex.types.integer(500),
  emphasizedDisplayLargeSize: stylex.types.integer(57),
  emphasizedDisplayLargeLineHeight: stylex.types.integer(64),
  emphasizedDisplayLargeTracking: stylex.types.number(-0.25),
  emphasizedDisplayLargeWght: stylex.types.integer(500),
  emphasizedDisplayLargeOpsz: stylex.types.integer(57),
  emphasizedDisplayLargeFontStyle: 'normal',
  emphasizedDisplayLargeTextTransform: 'none',
  emphasizedDisplayLargeTextDecoration: 'none',
  emphasizedDisplayLargeGrad: stylex.types.integer(0),
  emphasizedDisplayLargeWdth: stylex.types.integer(100),
  emphasizedDisplayLargeRond: stylex.types.integer(0),
  emphasizedDisplayLargeCrsv: stylex.types.integer(0),
  emphasizedDisplayLargeSlnt: stylex.types.integer(0),
  emphasizedDisplayLargeFill: stylex.types.integer(0),
  emphasizedDisplayLargeHexp: stylex.types.integer(0),

  emphasizedDisplayMediumFont: youRefTypeface.font,
  emphasizedDisplayMediumWeight: stylex.types.integer(500),
  emphasizedDisplayMediumSize: stylex.types.integer(45),
  emphasizedDisplayMediumLineHeight: stylex.types.integer(52),
  emphasizedDisplayMediumTracking: stylex.types.number(0),
  emphasizedDisplayMediumWght: stylex.types.integer(500),
  emphasizedDisplayMediumOpsz: stylex.types.integer(45),
  emphasizedDisplayMediumFontStyle: 'normal',
  emphasizedDisplayMediumTextTransform: 'none',
  emphasizedDisplayMediumTextDecoration: 'none',
  emphasizedDisplayMediumGrad: stylex.types.integer(0),
  emphasizedDisplayMediumWdth: stylex.types.integer(100),
  emphasizedDisplayMediumRond: stylex.types.integer(0),
  emphasizedDisplayMediumCrsv: stylex.types.integer(0),
  emphasizedDisplayMediumSlnt: stylex.types.integer(0),
  emphasizedDisplayMediumFill: stylex.types.integer(0),
  emphasizedDisplayMediumHexp: stylex.types.integer(0),

  emphasizedDisplaySmallFont: youRefTypeface.font,
  emphasizedDisplaySmallWeight: stylex.types.integer(500),
  emphasizedDisplaySmallSize: stylex.types.integer(36),
  emphasizedDisplaySmallLineHeight: stylex.types.integer(44),
  emphasizedDisplaySmallTracking: stylex.types.number(0),
  emphasizedDisplaySmallWght: stylex.types.integer(500),
  emphasizedDisplaySmallOpsz: stylex.types.integer(36),
  emphasizedDisplaySmallFontStyle: 'normal',
  emphasizedDisplaySmallTextTransform: 'none',
  emphasizedDisplaySmallTextDecoration: 'none',
  emphasizedDisplaySmallGrad: stylex.types.integer(0),
  emphasizedDisplaySmallWdth: stylex.types.integer(100),
  emphasizedDisplaySmallRond: stylex.types.integer(0),
  emphasizedDisplaySmallCrsv: stylex.types.integer(0),
  emphasizedDisplaySmallSlnt: stylex.types.integer(0),
  emphasizedDisplaySmallFill: stylex.types.integer(0),
  emphasizedDisplaySmallHexp: stylex.types.integer(0),

  emphasizedHeadlineLargeFont: youRefTypeface.font,
  emphasizedHeadlineLargeWeight: stylex.types.integer(500),
  emphasizedHeadlineLargeSize: stylex.types.integer(32),
  emphasizedHeadlineLargeLineHeight: stylex.types.integer(40),
  emphasizedHeadlineLargeTracking: stylex.types.number(0),
  emphasizedHeadlineLargeWght: stylex.types.integer(500),
  emphasizedHeadlineLargeOpsz: stylex.types.integer(32),
  emphasizedHeadlineLargeFontStyle: 'normal',
  emphasizedHeadlineLargeTextTransform: 'none',
  emphasizedHeadlineLargeTextDecoration: 'none',
  emphasizedHeadlineLargeGrad: stylex.types.integer(0),
  emphasizedHeadlineLargeWdth: stylex.types.integer(100),
  emphasizedHeadlineLargeRond: stylex.types.integer(0),
  emphasizedHeadlineLargeCrsv: stylex.types.integer(0),
  emphasizedHeadlineLargeSlnt: stylex.types.integer(0),
  emphasizedHeadlineLargeFill: stylex.types.integer(0),
  emphasizedHeadlineLargeHexp: stylex.types.integer(0),

  emphasizedHeadlineMediumFont: youRefTypeface.font,
  emphasizedHeadlineMediumWeight: stylex.types.integer(500),
  emphasizedHeadlineMediumSize: stylex.types.integer(28),
  emphasizedHeadlineMediumLineHeight: stylex.types.integer(36),
  emphasizedHeadlineMediumTracking: stylex.types.number(0),
  emphasizedHeadlineMediumWght: stylex.types.integer(500),
  emphasizedHeadlineMediumOpsz: stylex.types.integer(28),
  emphasizedHeadlineMediumFontStyle: 'normal',
  emphasizedHeadlineMediumTextTransform: 'none',
  emphasizedHeadlineMediumTextDecoration: 'none',
  emphasizedHeadlineMediumGrad: stylex.types.integer(0),
  emphasizedHeadlineMediumWdth: stylex.types.integer(100),
  emphasizedHeadlineMediumRond: stylex.types.integer(0),
  emphasizedHeadlineMediumCrsv: stylex.types.integer(0),
  emphasizedHeadlineMediumSlnt: stylex.types.integer(0),
  emphasizedHeadlineMediumFill: stylex.types.integer(0),
  emphasizedHeadlineMediumHexp: stylex.types.integer(0),

  emphasizedHeadlineSmallFont: youRefTypeface.font,
  emphasizedHeadlineSmallWeight: stylex.types.integer(500),
  emphasizedHeadlineSmallSize: stylex.types.integer(24),
  emphasizedHeadlineSmallLineHeight: stylex.types.integer(32),
  emphasizedHeadlineSmallTracking: stylex.types.number(0),
  emphasizedHeadlineSmallWght: stylex.types.integer(500),
  emphasizedHeadlineSmallOpsz: stylex.types.integer(24),
  emphasizedHeadlineSmallFontStyle: 'normal',
  emphasizedHeadlineSmallTextTransform: 'none',
  emphasizedHeadlineSmallTextDecoration: 'none',
  emphasizedHeadlineSmallGrad: stylex.types.integer(0),
  emphasizedHeadlineSmallWdth: stylex.types.integer(100),
  emphasizedHeadlineSmallRond: stylex.types.integer(0),
  emphasizedHeadlineSmallCrsv: stylex.types.integer(0),
  emphasizedHeadlineSmallSlnt: stylex.types.integer(0),
  emphasizedHeadlineSmallFill: stylex.types.integer(0),
  emphasizedHeadlineSmallHexp: stylex.types.integer(0),

  emphasizedTitleLargeFont: youRefTypeface.font,
  emphasizedTitleLargeWeight: stylex.types.integer(500),
  emphasizedTitleLargeSize: stylex.types.integer(22),
  emphasizedTitleLargeLineHeight: stylex.types.integer(28),
  emphasizedTitleLargeTracking: stylex.types.number(0),
  emphasizedTitleLargeWght: stylex.types.integer(500),
  emphasizedTitleLargeOpsz: stylex.types.integer(22),
  emphasizedTitleLargeFontStyle: 'normal',
  emphasizedTitleLargeTextTransform: 'none',
  emphasizedTitleLargeTextDecoration: 'none',
  emphasizedTitleLargeGrad: stylex.types.integer(0),
  emphasizedTitleLargeWdth: stylex.types.integer(100),
  emphasizedTitleLargeRond: stylex.types.integer(0),
  emphasizedTitleLargeCrsv: stylex.types.integer(0),
  emphasizedTitleLargeSlnt: stylex.types.integer(0),
  emphasizedTitleLargeFill: stylex.types.integer(0),
  emphasizedTitleLargeHexp: stylex.types.integer(0),

  emphasizedTitleMediumFont: youRefTypeface.font,
  emphasizedTitleMediumWeight: stylex.types.integer(700),
  emphasizedTitleMediumSize: stylex.types.integer(16),
  emphasizedTitleMediumLineHeight: stylex.types.integer(24),
  emphasizedTitleMediumTracking: stylex.types.number(0.15),
  emphasizedTitleMediumWght: stylex.types.integer(600),
  emphasizedTitleMediumOpsz: stylex.types.integer(16),
  emphasizedTitleMediumFontStyle: 'normal',
  emphasizedTitleMediumTextTransform: 'none',
  emphasizedTitleMediumTextDecoration: 'none',
  emphasizedTitleMediumGrad: stylex.types.integer(0),
  emphasizedTitleMediumWdth: stylex.types.integer(100),
  emphasizedTitleMediumRond: stylex.types.integer(0),
  emphasizedTitleMediumCrsv: stylex.types.integer(0),
  emphasizedTitleMediumSlnt: stylex.types.integer(0),
  emphasizedTitleMediumFill: stylex.types.integer(0),
  emphasizedTitleMediumHexp: stylex.types.integer(0),

  emphasizedTitleSmallFont: youRefTypeface.font,
  emphasizedTitleSmallWeight: stylex.types.integer(700),
  emphasizedTitleSmallSize: stylex.types.integer(14),
  emphasizedTitleSmallLineHeight: stylex.types.integer(20),
  emphasizedTitleSmallTracking: stylex.types.number(0.1),
  emphasizedTitleSmallWght: stylex.types.integer(600),
  emphasizedTitleSmallOpsz: stylex.types.integer(14),
  emphasizedTitleSmallFontStyle: 'normal',
  emphasizedTitleSmallTextTransform: 'none',
  emphasizedTitleSmallTextDecoration: 'none',
  emphasizedTitleSmallGrad: stylex.types.integer(0),
  emphasizedTitleSmallWdth: stylex.types.integer(100),
  emphasizedTitleSmallRond: stylex.types.integer(0),
  emphasizedTitleSmallCrsv: stylex.types.integer(0),
  emphasizedTitleSmallSlnt: stylex.types.integer(0),
  emphasizedTitleSmallFill: stylex.types.integer(0),
  emphasizedTitleSmallHexp: stylex.types.integer(0),

  emphasizedBodyLargeFont: youRefTypeface.font,
  emphasizedBodyLargeWeight: stylex.types.integer(500),
  emphasizedBodyLargeSize: stylex.types.integer(16),
  emphasizedBodyLargeLineHeight: stylex.types.integer(24),
  emphasizedBodyLargeTracking: stylex.types.number(0.5),
  emphasizedBodyLargeWght: stylex.types.integer(500),
  emphasizedBodyLargeOpsz: stylex.types.integer(16),
  emphasizedBodyLargeFontStyle: 'normal',
  emphasizedBodyLargeTextTransform: 'none',
  emphasizedBodyLargeTextDecoration: 'none',
  emphasizedBodyLargeGrad: stylex.types.integer(0),
  emphasizedBodyLargeWdth: stylex.types.integer(100),
  emphasizedBodyLargeRond: stylex.types.integer(0),
  emphasizedBodyLargeCrsv: stylex.types.integer(0),
  emphasizedBodyLargeSlnt: stylex.types.integer(0),
  emphasizedBodyLargeFill: stylex.types.integer(0),
  emphasizedBodyLargeHexp: stylex.types.integer(0),

  emphasizedBodyMediumFont: youRefTypeface.font,
  emphasizedBodyMediumWeight: stylex.types.integer(500),
  emphasizedBodyMediumSize: stylex.types.integer(14),
  emphasizedBodyMediumLineHeight: stylex.types.integer(20),
  emphasizedBodyMediumTracking: stylex.types.number(0.25),
  emphasizedBodyMediumWght: stylex.types.integer(500),
  emphasizedBodyMediumOpsz: stylex.types.integer(14),
  emphasizedBodyMediumFontStyle: 'normal',
  emphasizedBodyMediumTextTransform: 'none',
  emphasizedBodyMediumTextDecoration: 'none',
  emphasizedBodyMediumGrad: stylex.types.integer(0),
  emphasizedBodyMediumWdth: stylex.types.integer(100),
  emphasizedBodyMediumRond: stylex.types.integer(0),
  emphasizedBodyMediumCrsv: stylex.types.integer(0),
  emphasizedBodyMediumSlnt: stylex.types.integer(0),
  emphasizedBodyMediumFill: stylex.types.integer(0),
  emphasizedBodyMediumHexp: stylex.types.integer(0),

  emphasizedBodySmallFont: youRefTypeface.font,
  emphasizedBodySmallWeight: stylex.types.integer(500),
  emphasizedBodySmallSize: stylex.types.integer(12),
  emphasizedBodySmallLineHeight: stylex.types.integer(16),
  emphasizedBodySmallTracking: stylex.types.number(0.4),
  emphasizedBodySmallWght: stylex.types.integer(500),
  emphasizedBodySmallOpsz: stylex.types.integer(12),
  emphasizedBodySmallFontStyle: 'normal',
  emphasizedBodySmallTextTransform: 'none',
  emphasizedBodySmallTextDecoration: 'none',
  emphasizedBodySmallGrad: stylex.types.integer(0),
  emphasizedBodySmallWdth: stylex.types.integer(100),
  emphasizedBodySmallRond: stylex.types.integer(0),
  emphasizedBodySmallCrsv: stylex.types.integer(0),
  emphasizedBodySmallSlnt: stylex.types.integer(0),
  emphasizedBodySmallFill: stylex.types.integer(0),
  emphasizedBodySmallHexp: stylex.types.integer(0),

  emphasizedLabelLargeFont: youRefTypeface.font,
  emphasizedLabelLargeWeight: stylex.types.integer(700),
  emphasizedLabelLargeSize: stylex.types.integer(14),
  emphasizedLabelLargeLineHeight: stylex.types.integer(20),
  emphasizedLabelLargeTracking: stylex.types.number(0.1),
  emphasizedLabelLargeWght: stylex.types.integer(600),
  emphasizedLabelLargeOpsz: stylex.types.integer(14),
  emphasizedLabelLargeFontStyle: 'normal',
  emphasizedLabelLargeTextTransform: 'none',
  emphasizedLabelLargeTextDecoration: 'none',
  emphasizedLabelLargeGrad: stylex.types.integer(0),
  emphasizedLabelLargeWdth: stylex.types.integer(100),
  emphasizedLabelLargeRond: stylex.types.integer(0),
  emphasizedLabelLargeCrsv: stylex.types.integer(0),
  emphasizedLabelLargeSlnt: stylex.types.integer(0),
  emphasizedLabelLargeFill: stylex.types.integer(0),
  emphasizedLabelLargeHexp: stylex.types.integer(0),

  emphasizedLabelMediumFont: youRefTypeface.font,
  emphasizedLabelMediumWeight: stylex.types.integer(700),
  emphasizedLabelMediumSize: stylex.types.integer(12),
  emphasizedLabelMediumLineHeight: stylex.types.integer(16),
  emphasizedLabelMediumTracking: stylex.types.number(0.5),
  emphasizedLabelMediumWght: stylex.types.integer(600),
  emphasizedLabelMediumOpsz: stylex.types.integer(12),
  emphasizedLabelMediumFontStyle: 'normal',
  emphasizedLabelMediumTextTransform: 'none',
  emphasizedLabelMediumTextDecoration: 'none',
  emphasizedLabelMediumGrad: stylex.types.integer(0),
  emphasizedLabelMediumWdth: stylex.types.integer(100),
  emphasizedLabelMediumRond: stylex.types.integer(0),
  emphasizedLabelMediumCrsv: stylex.types.integer(0),
  emphasizedLabelMediumSlnt: stylex.types.integer(0),
  emphasizedLabelMediumFill: stylex.types.integer(0),
  emphasizedLabelMediumHexp: stylex.types.integer(0),

  emphasizedLabelSmallFont: youRefTypeface.font,
  emphasizedLabelSmallWeight: stylex.types.integer(700),
  emphasizedLabelSmallSize: stylex.types.integer(11),
  emphasizedLabelSmallLineHeight: stylex.types.integer(16),
  emphasizedLabelSmallTracking: stylex.types.number(0.5),
  emphasizedLabelSmallWght: stylex.types.integer(600),
  emphasizedLabelSmallOpsz: stylex.types.integer(11),
  emphasizedLabelSmallFontStyle: 'normal',
  emphasizedLabelSmallTextTransform: 'none',
  emphasizedLabelSmallTextDecoration: 'none',
  emphasizedLabelSmallGrad: stylex.types.integer(0),
  emphasizedLabelSmallWdth: stylex.types.integer(100),
  emphasizedLabelSmallRond: stylex.types.integer(0),
  emphasizedLabelSmallCrsv: stylex.types.integer(0),
  emphasizedLabelSmallSlnt: stylex.types.integer(0),
  emphasizedLabelSmallFill: stylex.types.integer(0),
  emphasizedLabelSmallHexp: stylex.types.integer(0),
});
